// @ts-ignore - No types available for vader-sentiment
import * as vader from 'vader-sentiment'

export interface VADERAnalysis {
    sentiment_label: 'Positive' | 'Negative' | 'Neutral'
    compound_score: number
    positive: number
    negative: number
    neutral: number
    confidence: number
    keywords: string[]
    emoji_count: number
    processed_text: string
}

export interface DebateContext {
    title: string
    description: string
    tags: string[]
}

export class VADERSentimentService {
    private enhancedLexicon: { [key: string]: number } = {
        // Strong Positive English Words
        'amazing': 2.8,
        'awesome': 2.6,
        'excellent': 2.9,
        'outstanding': 2.7,
        'fantastic': 2.8,
        'wonderful': 2.5,
        'brilliant': 2.6,
        'superb': 2.4,
        'magnificent': 2.7,
        'spectacular': 2.8,
        'incredible': 2.6,
        'phenomenal': 2.9,
        'extraordinary': 2.8,
        'marvelous': 2.5,
        'terrific': 2.4,
        'fabulous': 2.6,
        'splendid': 2.3,
        'remarkable': 2.4,
        'impressive': 2.2,
        'perfect': 2.9,
        'flawless': 2.7,
        'beautiful': 2.3,
        'gorgeous': 2.5,
        'stunning': 2.6,
        'breathtaking': 2.8,
        'delightful': 2.2,

        // Positive action/step words
        'step': 1.6,
        'steps': 1.6,
        'positive': 2.1,
        'promote': 1.8,
        'promotes': 1.8,
        'promoting': 1.8,
        'reduce': 1.4,
        'reduces': 1.4,
        'reducing': 1.4,
        'improve': 1.7,
        'improves': 1.7,
        'improving': 1.7,
        'enhance': 1.6,
        'enhances': 1.6,
        'enhancing': 1.6,
        'benefit': 1.8,
        'benefits': 1.8,
        'beneficial': 1.8,
        'advance': 1.5,
        'advances': 1.5,
        'advancing': 1.5,
        'forward': 1.3,
        'progress': 1.8,
        'progressive': 1.7,
        'initiative': 1.8,
        'initiatives': 1.8,

        // Governance and Policy Positive Words
        'commendable': 2.4,
        'praiseworthy': 2.3,
        'laudable': 2.2,
        'admirable': 2.1,
        'exemplary': 2.5,
        'noteworthy': 2.0,
        'meritorious': 2.2,
        'creditable': 2.0,
        'ensures': 1.9,
        'guarantees': 2.0,
        'secures': 1.8,
        'safeguards': 1.9,
        'protects': 1.7,
        'strengthens': 1.8,
        'reinforces': 1.6,
        'supports': 1.7,
        'facilitates': 1.5,
        'enables': 1.6,
        'empowers': 1.9,
        'fosters': 1.7,
        'encourages': 1.6,
        'motivates': 1.7,
        'inspires': 1.8,
        'drives': 1.4,
        'leads': 1.3,
        'pioneers': 1.9,
        'spearheads': 1.8,
        'champions': 2.0,
        'advocates': 1.7,
        'endorses': 1.6,

        // International Relations & Compliance Positive
        'complies': 1.8,
        'compliance': 1.8,
        'adheres': 1.7,
        'adherence': 1.7,
        'conforms': 1.5,
        'conformity': 1.5,
        'meets': 1.6,
        'fulfills': 1.8,
        'satisfies': 1.7,
        'achieves': 1.9,
        'attains': 1.8,
        'realizes': 1.6,
        'accomplishes': 1.9,
        'delivers': 1.7,
        'implements': 1.6,
        'executes': 1.4,
        'upholds': 1.8,
        'maintains': 1.4,
        'observes': 1.3,
        'respects': 1.6,
        'honors': 1.7,
        'abides': 1.5,
        'follows': 1.3,
        'international': 0.8,
        'global': 0.9,
        'worldwide': 0.8,
        'universal': 1.2,
        'multilateral': 1.1,
        'cooperative': 1.6,
        'collaborative': 1.7,
        'partnership': 1.5,
        'alliance': 1.4,
        'treaty': 0.9,
        'agreement': 1.2,
        'accord': 1.3,
        'pact': 1.0,
        'convention': 1.1,
        'protocol': 0.8,
        'framework': 1.0,
        'standard': 1.2,
        'standards': 1.2,
        'guidelines': 1.1,
        'principles': 1.4,
        'values': 1.3,
        'norms': 1.0,
        'rules': 0.8,
        'regulations': 0.7,
        'laws': 0.5,
        'legislation': 0.6,

        // SDG and Development Positive Words
        'sdg': 1.5,
        'sdgs': 1.5,
        'goals': 1.4,
        'targets': 1.2,
        'objectives': 1.3,
        'aims': 1.2,
        'aspirations': 1.4,
        'vision': 1.5,
        'mission': 1.4,
        'purpose': 1.2,
        'development': 1.6,
        'sustainable': 1.6,
        'sustainability': 1.6,
        'resilience': 1.5,
        'resilient': 1.5,
        'inclusive': 1.7,
        'equitable': 1.8,
        'fair': 1.6,
        'just': 1.5,
        'balanced': 1.4,
        'comprehensive': 1.3,
        'holistic': 1.4,
        'integrated': 1.3,
        'coordinated': 1.2,
        'systematic': 1.1,
        'strategic': 1.4,
        'effective': 1.5,
        'efficient': 1.5,
        'optimal': 1.6,
        'robust': 1.4,
        'solid': 1.3,
        'strong': 1.4,
        'powerful': 1.5,
        'impactful': 1.7,
        'meaningful': 1.6,
        'significant': 1.5,
        'substantial': 1.4,
        'considerable': 1.3,
        'notable': 1.4,
        'remarkable': 2.4,
        'exceptional': 2.3,
        'unprecedented': 1.8,
        'groundbreaking': 2.2,
        'innovative': 1.8,
        'creative': 1.6,
        'novel': 1.5,
        'pioneering': 1.9,
        'cutting-edge': 1.8,
        'state-of-the-art': 1.7,
        'modern': 1.2,
        'contemporary': 1.1,
        'advanced': 1.6,
        'sophisticated': 1.4,
        'refined': 1.3,
        'polished': 1.2,
        'mature': 1.1,
        'evolved': 1.3,
        'developed': 1.2,
        'established': 1.1,
        'proven': 1.5,
        'tested': 1.3,
        'validated': 1.4,
        'verified': 1.3,
        'confirmed': 1.2,
        'endorsed': 1.6,
        'approved': 1.5,
        'authorized': 1.3,
        'sanctioned': 1.2,
        'legitimate': 1.4,
        'legal': 1.1,
        'lawful': 1.2,
        'valid': 1.3,
        'sound': 1.4,
        'reasonable': 1.5,
        'rational': 1.4,
        'logical': 1.3,
        'sensible': 1.4,
        'practical': 1.3,
        'pragmatic': 1.2,
        'realistic': 1.1,
        'feasible': 1.4,
        'viable': 1.5,
        'workable': 1.4,
        'achievable': 1.6,
        'attainable': 1.5,
        'reachable': 1.4,
        'accessible': 1.3,
        'available': 1.1,
        'ready': 1.2,
        'prepared': 1.3,
        'equipped': 1.4,
        'capable': 1.5,
        'competent': 1.6,
        'qualified': 1.5,
        'skilled': 1.4,
        'experienced': 1.3,
        'knowledgeable': 1.4,
        'informed': 1.3,
        'aware': 1.2,
        'conscious': 1.3,
        'mindful': 1.4,
        'thoughtful': 1.5,
        'considerate': 1.6,
        'careful': 1.3,
        'cautious': 1.1,
        'prudent': 1.4,
        'wise': 1.6,
        'smart': 1.5,
        'intelligent': 1.4,
        'clever': 1.3,
        'bright': 1.4,
        'sharp': 1.3,
        'keen': 1.2,
        'alert': 1.1,
        'vigilant': 1.2,
        'watchful': 1.1,
        'attentive': 1.3,
        'focused': 1.4,
        'dedicated': 1.6,
        'committed': 1.7,
        'devoted': 1.6,
        'loyal': 1.4,
        'faithful': 1.5,
        'reliable': 1.5,
        'dependable': 1.6,
        'trustworthy': 1.7,
        'charming': 2.1,
        'lovely': 2.0,
        'adorable': 2.3,
        'inspiring': 2.4,
        'uplifting': 2.3,
        'motivating': 2.2,
        'encouraging': 2.1,
        'empowering': 2.4,
        'refreshing': 2.0,
        'invigorating': 2.2,
        'energizing': 2.1,
        'thrilling': 2.5,
        'exciting': 2.3,
        'exhilarating': 2.6,

        // Moderate Positive English Words
        'good': 1.8,
        'great': 2.0,
        'nice': 1.5,
        'fine': 1.3,
        'pleasant': 1.6,
        'enjoyable': 1.8,
        'satisfying': 1.7,
        'helpful': 1.6,
        'useful': 1.4,
        'valuable': 1.7,
        'beneficial': 1.8,
        'positive': 1.9,
        'constructive': 1.6,
        'productive': 1.7,
        'effective': 1.5,
        'successful': 2.0,
        'accomplished': 1.9,
        'achieved': 1.6,
        'improved': 1.7,
        'enhanced': 1.5,
        'better': 1.4,
        'superior': 1.8,
        'quality': 1.3,
        'reliable': 1.5,
        'trustworthy': 1.7,
        'honest': 1.6,
        'genuine': 1.4,
        'authentic': 1.5,
        'sincere': 1.6,
        'thoughtful': 1.5,
        'considerate': 1.6,
        'kind': 1.8,
        'generous': 1.7,
        'compassionate': 1.9,
        'caring': 1.8,
        'supportive': 1.9,
        'understanding': 1.6,
        'patient': 1.4,
        'respectful': 1.7,
        'polite': 1.3,
        'friendly': 1.6,
        'welcoming': 1.7,

        // Strong Negative English Words
        'terrible': -2.8,
        'horrible': -2.9,
        'awful': -2.7,
        'disgusting': -2.8,
        'revolting': -2.6,
        'repulsive': -2.7,
        'appalling': -2.8,
        'shocking': -2.4,
        'outrageous': -2.6,
        'unacceptable': -2.5,
        'intolerable': -2.7,
        'unbearable': -2.6,
        'devastating': -2.8,
        'catastrophic': -2.9,
        'disastrous': -2.7,
        'tragic': -2.5,
        'heartbreaking': -2.6,
        'depressing': -2.4,
        'miserable': -2.5,
        'pathetic': -2.3,
        'worthless': -2.6,
        'useless': -2.2,
        'pointless': -2.1,
        'meaningless': -2.0,
        'hopeless': -2.4,
        'helpless': -2.2,
        'powerless': -2.1,
        'defeated': -2.3,
        'failed': -2.2,
        'broken': -2.1,
        'damaged': -1.9,
        'ruined': -2.4,
        'destroyed': -2.5,
        'wasted': -2.0,
        'lost': -1.8,
        'doomed': -2.3,
        'cursed': -2.2,
        'damned': -2.4,
        'evil': -2.6,
        'wicked': -2.5,
        'cruel': -2.4,
        'vicious': -2.5,
        'brutal': -2.6,
        'savage': -2.4,
        'violent': -2.3,
        'aggressive': -2.1,
        'hostile': -2.2,
        'threatening': -2.3,
        'dangerous': -2.1,
        'harmful': -2.0,
        'toxic': -2.4,
        'poisonous': -2.3,

        // Moderate Negative English Words
        'bad': -1.8,
        'poor': -1.6,
        'weak': -1.5,
        'disappointing': -1.9,
        'unsatisfactory': -1.7,
        'inadequate': -1.6,
        'insufficient': -1.5,
        'lacking': -1.4,
        'missing': -1.3,
        'incomplete': -1.4,
        'unfinished': -1.3,
        'flawed': -1.6,
        'defective': -1.8,
        'faulty': -1.7,
        'incorrect': -1.4,
        'wrong': -1.5,
        'mistaken': -1.3,
        'confused': -1.2,
        'unclear': -1.1,
        'uncertain': -1.0,
        'doubtful': -1.2,
        'questionable': -1.3,
        'suspicious': -1.4,
        'unreliable': -1.6,
        'untrustworthy': -1.8,
        'dishonest': -1.9,
        'fake': -1.7,
        'false': -1.6,
        'misleading': -1.5,
        'deceptive': -1.7,
        'manipulative': -1.8,
        'selfish': -1.6,
        'greedy': -1.7,
        'arrogant': -1.8,
        'rude': -1.6,
        'impolite': -1.4,
        'disrespectful': -1.7,
        'inconsiderate': -1.5,
        'thoughtless': -1.4,
        'careless': -1.3,
        'negligent': -1.5,
        'irresponsible': -1.6,
        'immature': -1.4,
        'childish': -1.3,
        'silly': -0.8,
        'foolish': -1.2,
        'stupid': -1.8,
        'ignorant': -1.6,
        'narrow-minded': -1.5,
        'biased': -1.4,
        'prejudiced': -1.7,
        'discriminatory': -1.9,

        // Governance and Policy Negative Words
        'condemnable': -2.4,
        'deplorable': -2.5,
        'reprehensible': -2.3,
        'inexcusable': -2.2,
        'unacceptable': -2.5,
        'intolerable': -2.7,
        'objectionable': -2.1,
        'offensive': -2.0,
        'inappropriate': -1.8,
        'improper': -1.7,
        'unsuitable': -1.6,
        'unfit': -1.8,
        'incompetent': -2.0,
        'incapable': -1.9,
        'unable': -1.5,
        'powerless': -2.1,
        'helpless': -2.2,
        'ineffective': -1.9,
        'inefficient': -1.8,
        'ineffectual': -1.9,
        'futile': -2.1,
        'useless': -2.2,
        'pointless': -2.1,
        'meaningless': -2.0,
        'worthless': -2.6,
        'valueless': -2.3,
        'insignificant': -1.7,
        'trivial': -1.5,
        'minor': -1.2,
        'negligible': -1.4,
        'minimal': -1.3,
        'limited': -1.2,
        'restricted': -1.3,
        'constrained': -1.4,
        'hindered': -1.6,
        'obstructed': -1.7,
        'blocked': -1.8,
        'prevented': -1.6,
        'stopped': -1.5,
        'halted': -1.6,
        'suspended': -1.4,
        'cancelled': -1.7,
        'terminated': -1.8,
        'ended': -1.3,
        'ceased': -1.4,
        'discontinued': -1.5,
        'abandoned': -1.9,
        'forsaken': -2.0,
        'neglected': -1.8,
        'ignored': -1.7,
        'overlooked': -1.5,
        'disregarded': -1.6,
        'dismissed': -1.7,
        'rejected': -1.8,
        'refused': -1.6,
        'denied': -1.7,
        'declined': -1.4,
        'opposed': -1.5,
        'resisted': -1.4,
        'contested': -1.3,
        'challenged': -1.1,
        'disputed': -1.2,
        'questioned': -0.9,
        'criticized': -1.4,
        'condemned': -2.0,
        'denounced': -2.1,
        'censured': -1.9,
        'blamed': -1.6,
        'accused': -1.7,
        'charged': -1.5,
        'indicted': -1.8,
        'prosecuted': -1.6,
        'punished': -1.7,
        'penalized': -1.6,
        'sanctioned': -1.5,
        'fined': -1.4,
        'suspended': -1.4,
        'banned': -1.8,
        'prohibited': -1.6,
        'forbidden': -1.7,
        'restricted': -1.3,
        'limited': -1.2,
        'controlled': -1.1,
        'regulated': -0.8,
        'monitored': -0.6,
        'supervised': -0.5,
        'overseen': -0.4,
        'managed': -0.2,
        'administered': -0.1,

        // International Relations & Compliance Negative
        'violates': -2.2,
        'violation': -2.2,
        'breaches': -2.0,
        'breach': -2.0,
        'infringes': -1.9,
        'infringement': -1.9,
        'contravenes': -1.8,
        'contravention': -1.8,
        'transgresses': -1.9,
        'transgression': -1.9,
        'defaults': -1.7,
        'default': -1.7,
        'fails': -1.8,
        'failure': -2.0,
        'neglects': -1.6,
        'neglect': -1.6,
        'omits': -1.4,
        'omission': -1.4,
        'overlooks': -1.3,
        'oversight': -1.2,
        'misses': -1.3,
        'ignores': -1.7,
        'disregards': -1.6,
        'dismisses': -1.7,
        'rejects': -1.8,
        'refuses': -1.6,
        'declines': -1.4,
        'denies': -1.7,
        'opposes': -1.5,
        'resists': -1.4,
        'contests': -1.3,
        'challenges': -1.1,
        'disputes': -1.2,
        'questions': -0.9,
        'doubts': -1.2,
        'suspects': -1.3,
        'mistrusts': -1.6,
        'distrusts': -1.7,
        'disbelieves': -1.5,
        'discredits': -1.8,
        'undermines': -2.0,
        'weakens': -1.7,
        'damages': -1.9,
        'harms': -2.0,
        'hurts': -1.8,
        'injures': -1.9,
        'wounds': -1.8,
        'impairs': -1.7,
        'compromises': -1.6,
        'jeopardizes': -1.8,
        'endangers': -2.0,
        'threatens': -2.3,
        'menaces': -2.1,
        'intimidates': -2.0,
        'bullies': -2.2,
        'coerces': -2.1,
        'forces': -1.8,
        'compels': -1.7,
        'pressures': -1.6,
        'pushes': -1.4,
        'drives': -1.2,
        'motivates': -0.8,
        'encourages': -0.5,
        'supports': -0.2,
        'helps': 0.2,
        'assists': 0.4,
        'aids': 0.5,
        'facilitates': 0.7,
        'enables': 0.8,
        'empowers': 1.0,

        // Failure and Incompetence Words
        'incompetence': -2.1,
        'ineptitude': -2.0,
        'inability': -1.8,
        'incapacity': -1.9,
        'inadequacy': -1.6,
        'insufficiency': -1.5,
        'deficiency': -1.7,
        'shortage': -1.4,
        'lack': -1.4,
        'absence': -1.3,
        'void': -1.5,
        'gap': -1.2,
        'hole': -1.3,
        'flaw': -1.6,
        'defect': -1.8,
        'fault': -1.7,
        'error': -1.5,
        'mistake': -1.3,
        'blunder': -1.8,
        'oversight': -1.2,
        'slip': -1.1,
        'lapse': -1.3,
        'failure': -2.0,
        'collapse': -2.2,
        'breakdown': -2.1,
        'malfunction': -1.9,
        'dysfunction': -2.0,
        'disorder': -1.8,
        'chaos': -2.3,
        'confusion': -1.7,
        'mess': -1.9,
        'disaster': -2.7,
        'catastrophe': -2.9,
        'calamity': -2.6,
        'crisis': -2.2,
        'emergency': -1.8,
        'problem': -0.9,
        'issue': -0.4,
        'concern': -0.5,
        'worry': -1.2,
        'fear': -1.8,
        'anxiety': -1.6,
        'stress': -1.4,
        'tension': -1.0,
        'pressure': -0.8,
        'strain': -1.1,
        'burden': -1.4,
        'load': -0.9,
        'weight': -0.7,
        'responsibility': -0.2,
        'duty': 0.1,
        'obligation': 0.0,
        'requirement': -0.1,
        'necessity': -0.2,
        'need': -0.3,
        'demand': -0.5,
        'request': -0.1,
        'ask': 0.0,
        'seek': 0.2,
        'search': 0.3,
        'look': 0.1,
        'find': 0.4,
        'discover': 0.6,
        'uncover': 0.5,
        'reveal': 0.4,
        'expose': 0.2,
        'show': 0.3,
        'display': 0.2,
        'demonstrate': 0.5,
        'prove': 0.7,
        'establish': 0.6,
        'confirm': 0.5,
        'verify': 0.4,
        'validate': 0.5,
        'authenticate': 0.4,
        'certify': 0.6,
        'approve': 0.8,
        'endorse': 0.9,
        'support': 1.0,
        'back': 0.8,
        'champion': 1.2,
        'advocate': 1.0,
        'promote': 1.1,
        'advance': 0.9,
        'further': 0.8,
        'develop': 0.7,
        'improve': 1.0,
        'enhance': 0.9,
        'upgrade': 0.8,
        'modernize': 0.7,
        'update': 0.6,
        'revise': 0.4,
        'modify': 0.3,
        'change': 0.2,
        'alter': 0.1,
        'adjust': 0.2,
        'adapt': 0.4,
        'accommodate': 0.5,
        'include': 0.6,
        'incorporate': 0.5,
        'integrate': 0.6,
        'combine': 0.4,
        'merge': 0.3,
        'unite': 0.7,
        'join': 0.5,
        'connect': 0.4,
        'link': 0.3,
        'relate': 0.2,
        'associate': 0.1,
        'correlate': 0.2,
        'correspond': 0.1,
        'match': 0.3,
        'fit': 0.2,
        'suit': 0.3,
        'appropriate': 0.4,
        'suitable': 0.5,
        'proper': 0.4,
        'correct': 0.6,
        'right': 0.7,
        'accurate': 0.6,
        'precise': 0.5,
        'exact': 0.4,
        'specific': 0.3,
        'particular': 0.2,
        'special': 0.5,
        'unique': 0.6,
        'distinctive': 0.5,
        'characteristic': 0.3,
        'typical': 0.2,
        'normal': 0.1,
        'standard': 0.2,
        'regular': 0.1,
        'ordinary': 0.0,
        'common': -0.1,
        'usual': 0.0,
        'conventional': -0.1,
        'traditional': 0.0,
        'established': 0.2,
        'recognized': 0.4,
        'accepted': 0.5,
        'acknowledged': 0.4,
        'admitted': 0.2,
        'confessed': 0.1,
        'declared': 0.3,
        'announced': 0.2,
        'proclaimed': 0.4,
        'stated': 0.1,
        'said': 0.0,
        'mentioned': 0.0,
        'noted': 0.1,
        'observed': 0.2,
        'noticed': 0.1,
        'seen': 0.0,
        'viewed': 0.1,
        'regarded': 0.2,
        'considered': 0.1,
        'thought': 0.0,
        'believed': 0.1,
        'felt': 0.0,
        'sensed': 0.1,
        'perceived': 0.2,
        'understood': 0.3,
        'comprehended': 0.4,
        'grasped': 0.3,
        'realized': 0.4,
        'recognized': 0.4,
        'identified': 0.3,
        'distinguished': 0.2,
        'differentiated': 0.1,
        'separated': 0.0,
        'divided': -0.2,
        'split': -0.3,
        'broken': -1.5,
        'damaged': -1.9,
        'harmed': -2.0,
        'hurt': -1.8,
        'injured': -1.9,
        'wounded': -1.8,
        'impaired': -1.7,
        'compromised': -1.6,
        'jeopardized': -1.8,
        'endangered': -2.0,
        'threatened': -2.3,

        // === COMPREHENSIVE REAL-WORLD CONTEXTS ===

        // Technology & Innovation Positive
        'breakthrough': 2.2,
        'revolutionary': 2.4,
        'game-changer': 2.3,
        'disruptive': 1.8,
        'transformative': 2.1,
        'cutting-edge': 1.8,
        'state-of-the-art': 1.7,
        'next-generation': 1.6,
        'futuristic': 1.5,
        'high-tech': 1.4,
        'smart': 1.5,
        'intelligent': 1.4,
        'automated': 1.2,
        'streamlined': 1.4,
        'optimized': 1.5,
        'upgraded': 1.3,
        'enhanced': 1.5,
        'improved': 1.7,
        'faster': 1.4,
        'quicker': 1.3,
        'speedier': 1.2,
        'instant': 1.5,
        'immediate': 1.3,
        'real-time': 1.2,
        'seamless': 1.6,
        'smooth': 1.4,
        'fluid': 1.3,
        'intuitive': 1.5,
        'user-friendly': 1.6,
        'accessible': 1.3,
        'convenient': 1.5,
        'handy': 1.2,
        'useful': 1.4,
        'practical': 1.3,
        'functional': 1.2,
        'versatile': 1.4,
        'flexible': 1.3,
        'adaptable': 1.4,
        'scalable': 1.3,
        'robust': 1.4,
        'reliable': 1.5,
        'stable': 1.3,
        'secure': 1.6,
        'safe': 1.5,
        'protected': 1.4,

        // Social & Cultural Positive
        'inclusive': 1.7,
        'diverse': 1.4,
        'multicultural': 1.5,
        'tolerant': 1.6,
        'accepting': 1.7,
        'welcoming': 1.7,
        'open-minded': 1.8,
        'progressive': 1.7,
        'forward-thinking': 1.6,
        'modern': 1.2,
        'contemporary': 1.1,
        'trendy': 1.3,
        'fashionable': 1.2,
        'stylish': 1.4,
        'cool': 1.5,
        'hip': 1.3,
        'popular': 1.2,
        'trending': 1.3,
        'viral': 1.4,
        'buzzing': 1.5,
        'exciting': 2.3,
        'thrilling': 2.5,
        'exhilarating': 2.6,
        'electrifying': 2.4,
        'energizing': 2.1,
        'invigorating': 2.2,
        'refreshing': 2.0,
        'uplifting': 2.3,
        'inspiring': 2.4,
        'motivating': 2.2,
        'encouraging': 2.1,
        'empowering': 2.4,
        'liberating': 2.2,
        'freeing': 2.0,
        'enlightening': 2.1,
        'educational': 1.6,
        'informative': 1.5,
        'insightful': 1.7,
        'thought-provoking': 1.6,
        'eye-opening': 1.8,
        'revealing': 1.4,
        'illuminating': 1.6,

        // Economic & Business Positive
        'profitable': 1.8,
        'lucrative': 1.7,
        'cost-effective': 1.6,
        'economical': 1.4,
        'affordable': 1.5,
        'budget-friendly': 1.4,
        'value-for-money': 1.6,
        'worthwhile': 1.5,
        'beneficial': 1.8,
        'advantageous': 1.7,
        'favorable': 1.6,
        'promising': 1.8,
        'prosperous': 1.9,
        'thriving': 2.0,
        'flourishing': 2.1,
        'booming': 2.0,
        'growing': 1.6,
        'expanding': 1.5,
        'developing': 1.2,
        'emerging': 1.3,
        'rising': 1.4,
        'increasing': 1.2,
        'improving': 1.7,
        'recovering': 1.5,
        'stabilizing': 1.3,
        'strengthening': 1.8,
        'competitive': 1.4,
        'leading': 1.6,
        'dominant': 1.3,
        'successful': 2.0,
        'winning': 1.9,
        'victorious': 2.1,
        'triumphant': 2.2,

        // Health & Wellness Positive
        'healthy': 1.8,
        'fit': 1.6,
        'strong': 1.4,
        'energetic': 1.7,
        'vibrant': 1.8,
        'active': 1.5,
        'lively': 1.6,
        'vigorous': 1.5,
        'robust': 1.4,
        'resilient': 1.5,
        'recovered': 1.7,
        'healed': 1.8,
        'cured': 2.0,
        'treated': 1.4,
        'improved': 1.7,
        'better': 1.4,
        'wellness': 1.6,
        'wellbeing': 1.7,
        'fitness': 1.5,
        'nutrition': 1.3,
        'exercise': 1.4,
        'workout': 1.3,
        'training': 1.2,
        'therapy': 1.4,
        'treatment': 1.2,
        'medicine': 1.1,
        'cure': 2.0,
        'remedy': 1.6,
        'solution': 1.7,
        'relief': 1.3,
        'comfort': 1.2,
        'ease': 1.3,
        'peace': 1.8,
        'calm': 1.4,
        'relaxed': 1.5,
        'serene': 1.6,
        'tranquil': 1.5,
        'peaceful': 1.8,

        // Education & Learning Positive
        'educational': 1.6,
        'informative': 1.5,
        'enlightening': 2.1,
        'insightful': 1.7,
        'knowledgeable': 1.4,
        'learned': 1.5,
        'scholarly': 1.4,
        'academic': 1.2,
        'intellectual': 1.3,
        'smart': 1.5,
        'intelligent': 1.4,
        'bright': 1.4,
        'clever': 1.3,
        'wise': 1.6,
        'skilled': 1.4,
        'talented': 1.7,
        'gifted': 1.8,
        'capable': 1.5,
        'competent': 1.6,
        'qualified': 1.5,
        'experienced': 1.3,
        'expert': 1.6,
        'professional': 1.4,
        'masterful': 1.8,
        'proficient': 1.5,
        'accomplished': 1.9,
        'achieved': 1.6,
        'successful': 2.0,
        'graduated': 1.5,
        'certified': 1.4,
        'licensed': 1.3,
        'accredited': 1.4,
        'recognized': 1.3,
        'awarded': 1.6,
        'honored': 1.7,
        'distinguished': 1.8,

        // Entertainment & Leisure Positive
        'entertaining': 1.8,
        'amusing': 1.6,
        'funny': 1.7,
        'hilarious': 2.2,
        'humorous': 1.8,
        'witty': 1.6,
        'clever': 1.3,
        'charming': 2.1,
        'delightful': 2.2,
        'enjoyable': 1.8,
        'pleasant': 1.6,
        'fun': 1.9,
        'exciting': 2.3,
        'thrilling': 2.5,
        'adventurous': 1.9,
        'daring': 1.6,
        'bold': 1.5,
        'brave': 1.7,
        'courageous': 1.8,
        'fearless': 1.7,
        'confident': 1.4,
        'relaxing': 1.5,
        'soothing': 1.6,
        'calming': 1.4,
        'peaceful': 1.8,
        'tranquil': 1.5,
        'serene': 1.6,
        'beautiful': 2.3,
        'gorgeous': 2.5,
        'stunning': 2.6,
        'breathtaking': 2.8,
        'magnificent': 2.7,
        'spectacular': 2.8,
        'impressive': 2.2,
        'remarkable': 2.4,
        'extraordinary': 2.8,
        'incredible': 2.6,
        'amazing': 2.8,
        'wonderful': 2.5,
        'fantastic': 2.8,
        'marvelous': 2.5,
        'fabulous': 2.6,
        'superb': 2.4,
        'excellent': 2.9,
        'outstanding': 2.7,
        'exceptional': 2.3,
        'phenomenal': 2.9,
        'brilliant': 2.6,
        'genius': 2.4,
        'masterpiece': 2.7,
        'classic': 2.1,
        'timeless': 2.0,
        'legendary': 2.1,
        'iconic': 1.9,

        // Personal Relationships Positive
        'loving': 2.2,
        'caring': 1.8,
        'kind': 1.8,
        'gentle': 1.6,
        'sweet': 1.7,
        'tender': 1.6,
        'affectionate': 1.9,
        'warm': 1.5,
        'friendly': 1.6,
        'welcoming': 1.7,
        'hospitable': 1.6,
        'generous': 1.7,
        'giving': 1.6,
        'selfless': 1.8,
        'altruistic': 1.7,
        'compassionate': 1.9,
        'empathetic': 1.8,
        'understanding': 1.6,
        'supportive': 1.9,
        'encouraging': 2.1,
        'motivating': 2.2,
        'inspiring': 2.4,
        'uplifting': 2.3,
        'comforting': 1.7,
        'reassuring': 1.6,
        'trustworthy': 1.7,
        'reliable': 1.5,
        'dependable': 1.6,
        'loyal': 1.4,
        'faithful': 1.5,
        'devoted': 1.6,
        'committed': 1.7,
        'dedicated': 1.6,
        'passionate': 1.8,
        'enthusiastic': 1.8,
        'excited': 1.9,
        'thrilled': 2.5,
        'delighted': 2.2,
        'pleased': 1.6,
        'satisfied': 1.7,
        'content': 1.4,
        'happy': 2.4,
        'joyful': 2.2,
        'cheerful': 1.8,
        'optimistic': 1.7,
        'positive': 2.1,
        'hopeful': 1.8,
        'confident': 1.4,
        'proud': 1.2,
        'grateful': 1.9,
        'thankful': 1.8,
        'appreciative': 1.7,

        // Food & Lifestyle Positive
        'delicious': 2.3,
        'tasty': 2.0,
        'yummy': 1.9,
        'scrumptious': 2.2,
        'mouth-watering': 2.1,
        'appetizing': 1.8,
        'flavorful': 1.7,
        'savory': 1.6,
        'sweet': 1.7,
        'fresh': 1.5,
        'organic': 1.4,
        'natural': 1.3,
        'healthy': 1.8,
        'nutritious': 1.6,
        'wholesome': 1.5,
        'satisfying': 1.7,
        'filling': 1.2,
        'hearty': 1.4,
        'comforting': 1.7,
        'homemade': 1.5,
        'authentic': 1.5,
        'traditional': 0.5,
        'exotic': 1.3,
        'unique': 0.6,
        'special': 0.5,
        'gourmet': 1.6,
        'premium': 1.4,
        'luxury': 1.5,
        'elegant': 1.6,
        'sophisticated': 1.4,
        'classy': 1.5,
        'stylish': 1.4,
        'fashionable': 1.2,
        'trendy': 1.3,
        'chic': 1.4,
        'sleek': 1.3,
        'modern': 1.2,
        'contemporary': 1.1,
        'minimalist': 1.0,
        'clean': 1.4,
        'neat': 1.2,
        'organized': 1.3,
        'tidy': 1.1,
        'orderly': 1.2,
        'systematic': 1.1,
        'efficient': 1.5,
        'productive': 1.7,
        'effective': 1.5,
        'successful': 2.0,

        // Positive Indian slang
        'jhakaas': 2.5,
        'zabardast': 2.3,
        'kamaal': 2.1,
        'badhiya': 1.8,
        'accha': 1.5,
        'sahi': 1.3,
        'lit': 2.0,
        'fire': 2.2,
        'dope': 1.9,
        'sick': 2.1, // in positive context
        'based': 1.7,
        'goat': 2.0, // greatest of all time
        'slaps': 1.8,
        'hits': 1.6,
        'vibes': 1.4,
        'facts': 1.5,
        'periodt': 1.8,
        'slay': 2.0,
        'iconic': 1.9,
        'legend': 2.1,

        // === COMPREHENSIVE NEGATIVE CONTEXTS ===

        // Technology & Innovation Negative
        'outdated': -1.8,
        'obsolete': -2.0,
        'ancient': -1.6,
        'old-fashioned': -1.4,
        'primitive': -1.7,
        'backward': -1.5,
        'slow': -1.3,
        'sluggish': -1.5,
        'laggy': -1.4,
        'glitchy': -1.6,
        'buggy': -1.7,
        'broken': -2.1,
        'crashed': -1.9,
        'frozen': -1.5,
        'stuck': -1.4,
        'jammed': -1.3,
        'blocked': -1.8,
        'restricted': -1.3,
        'limited': -1.2,
        'constrained': -1.4,
        'complicated': -1.2,
        'complex': -0.8,
        'confusing': -1.7,
        'unclear': -1.1,
        'ambiguous': -1.0,
        'vague': -1.1,
        'uncertain': -1.0,
        'unreliable': -1.6,
        'unstable': -1.7,
        'insecure': -1.8,
        'vulnerable': -1.6,
        'risky': -1.5,
        'dangerous': -2.1,
        'unsafe': -1.9,
        'hazardous': -2.0,
        'threatening': -2.3,
        'malicious': -2.2,
        'harmful': -2.0,
        'destructive': -2.4,
        'damaging': -1.9,

        // Social & Cultural Negative
        'discriminatory': -1.9,
        'prejudiced': -1.7,
        'biased': -1.4,
        'unfair': -1.8,
        'unjust': -1.9,
        'inequitable': -1.7,
        'exclusive': -1.5,
        'elitist': -1.6,
        'snobbish': -1.7,
        'arrogant': -1.8,
        'condescending': -1.9,
        'patronizing': -1.8,
        'dismissive': -1.7,
        'disrespectful': -1.7,
        'rude': -1.6,
        'impolite': -1.4,
        'offensive': -2.0,
        'insulting': -2.1,
        'degrading': -2.2,
        'humiliating': -2.3,
        'embarrassing': -1.8,
        'shameful': -2.0,
        'disgraceful': -2.2,
        'scandalous': -2.1,
        'controversial': -1.2,
        'divisive': -1.6,
        'polarizing': -1.4,
        'contentious': -1.3,
        'disputed': -1.2,
        'questionable': -1.3,
        'suspicious': -1.4,
        'doubtful': -1.2,
        'skeptical': -1.0,
        'cynical': -1.3,
        'pessimistic': -1.5,
        'negative': -1.8,
        'gloomy': -1.6,
        'depressing': -2.4,
        'sad': -1.8,
        'miserable': -2.5,
        'unhappy': -2.0,
        'disappointed': -1.9,
        'frustrated': -1.8,
        'annoyed': -1.5,
        'irritated': -1.6,
        'angry': -2.0,
        'furious': -2.4,
        'outraged': -2.6,
        'enraged': -2.5,
        'livid': -2.3,
        'mad': -2.0,
        'upset': -1.7,
        'distressed': -2.1,
        'troubled': -1.8,
        'worried': -1.2,
        'anxious': -1.6,
        'nervous': -1.4,
        'scared': -1.8,
        'afraid': -1.8,
        'fearful': -1.8,
        'terrified': -2.4,
        'horrified': -2.5,
        'shocked': -2.4,
        'stunned': -1.9,
        'surprised': -0.5,
        'confused': -1.2,
        'bewildered': -1.4,
        'perplexed': -1.3,
        'puzzled': -1.1,
        'lost': -1.8,
        'helpless': -2.2,
        'hopeless': -2.4,
        'desperate': -2.3,
        'devastated': -2.8,
        'heartbroken': -2.6,
        'crushed': -2.4,
        'shattered': -2.5,
        'broken': -2.1,
        'damaged': -1.9,
        'hurt': -1.8,
        'wounded': -1.8,
        'injured': -1.9,
        'harmed': -2.0,
        'abused': -2.6,
        'mistreated': -2.3,
        'neglected': -1.8,
        'abandoned': -1.9,
        'rejected': -1.8,
        'ignored': -1.7,
        'dismissed': -1.7,
        'overlooked': -1.5,
        'forgotten': -1.6,
        'excluded': -1.8,
        'isolated': -2.0,
        'lonely': -2.1,
        'alone': -1.5,
        'separated': -1.4,
        'divorced': -1.6,
        'single': -0.3,
        'unmarried': -0.2,
        'widowed': -1.8,
        'orphaned': -2.2,

        // Economic & Business Negative
        'expensive': -1.4,
        'costly': -1.5,
        'overpriced': -1.8,
        'unaffordable': -2.0,
        'broke': -2.1,
        'bankrupt': -2.4,
        'insolvent': -2.3,
        'debt': -1.6,
        'loan': -0.8,
        'mortgage': -0.5,
        'payment': -0.3,
        'bill': -0.7,
        'tax': -0.9,
        'fine': -1.4,
        'penalty': -1.6,
        'fee': -0.8,
        'charge': -0.9,
        'cost': -0.6,
        'price': -0.2,
        'budget': -0.1,
        'cheap': -0.8,
        'low-quality': -1.7,
        'inferior': -1.8,
        'substandard': -1.9,
        'poor': -1.6,
        'bad': -1.8,
        'terrible': -2.8,
        'awful': -2.7,
        'horrible': -2.9,
        'disgusting': -2.8,
        'revolting': -2.6,
        'repulsive': -2.7,
        'appalling': -2.8,
        'shocking': -2.4,
        'outrageous': -2.6,
        'unacceptable': -2.5,
        'intolerable': -2.7,
        'unbearable': -2.6,
        'insufferable': -2.4,
        'annoying': -1.5,
        'irritating': -1.6,
        'frustrating': -1.8,
        'aggravating': -1.7,
        'bothersome': -1.4,
        'troublesome': -1.6,
        'problematic': -1.7,
        'difficult': -1.3,
        'hard': -1.0,
        'tough': -0.8,
        'challenging': 0.0,
        'demanding': -0.5,
        'stressful': -1.4,
        'overwhelming': -2.0,
        'exhausting': -1.9,
        'tiring': -1.5,
        'draining': -1.8,
        'depleting': -1.7,
        'consuming': -1.2,
        'wasteful': -1.6,
        'inefficient': -1.8,
        'ineffective': -1.9,
        'useless': -2.2,
        'pointless': -2.1,
        'meaningless': -2.0,
        'worthless': -2.6,
        'valueless': -2.3,
        'insignificant': -1.7,
        'trivial': -1.5,
        'unimportant': -1.6,
        'irrelevant': -1.4,
        'unnecessary': -1.3,
        'redundant': -1.2,
        'superfluous': -1.1,
        'excessive': -1.4,
        'too much': -1.2,
        'overboard': -1.3,
        'extreme': -1.1,
        'radical': -0.8,
        'drastic': -1.0,
        'severe': -1.6,
        'harsh': -1.7,
        'cruel': -2.4,
        'brutal': -2.6,
        'savage': -2.4,
        'vicious': -2.5,
        'violent': -2.3,
        'aggressive': -2.1,
        'hostile': -2.2,
        'threatening': -2.3,
        'intimidating': -2.0,
        'scary': -1.9,
        'frightening': -2.1,
        'terrifying': -2.4,
        'horrifying': -2.5,
        'disturbing': -2.2,
        'unsettling': -1.8,
        'uncomfortable': -1.5,
        'awkward': -1.3,
        'embarrassing': -1.8,
        'humiliating': -2.3,
        'degrading': -2.2,
        'demeaning': -2.1,
        'insulting': -2.1,
        'offensive': -2.0,
        'inappropriate': -1.8,
        'improper': -1.7,
        'wrong': -1.5,
        'incorrect': -1.4,
        'false': -1.6,
        'untrue': -1.5,
        'fake': -1.7,
        'fraudulent': -2.2,
        'deceptive': -1.7,
        'misleading': -1.5,
        'dishonest': -1.9,
        'lying': -2.0,
        'cheating': -2.1,
        'stealing': -2.3,
        'criminal': -2.4,
        'illegal': -2.0,
        'unlawful': -1.9,
        'forbidden': -1.7,
        'prohibited': -1.6,
        'banned': -1.8,
        'restricted': -1.3,
        'limited': -1.2,
        'controlled': -1.1,
        'regulated': -0.8,
        'monitored': -0.6,
        'supervised': -0.5,
        'watched': -0.7,
        'observed': -0.4,
        'tracked': -0.8,
        'followed': -0.6,
        'pursued': -0.5,
        'chased': -1.2,
        'hunted': -1.4,
        'stalked': -2.0,
        'harassed': -2.2,
        'bothered': -1.4,
        'pestered': -1.5,
        'annoyed': -1.5,
        'disturbed': -1.6,
        'interrupted': -1.2,
        'disrupted': -1.5,
        'interfered': -1.4,
        'obstructed': -1.7,
        'blocked': -1.8,
        'prevented': -1.6,
        'stopped': -1.5,
        'halted': -1.6,
        'ceased': -1.4,
        'ended': -1.3,
        'finished': -0.8,
        'completed': 0.5,
        'done': 0.2,
        'over': -0.5,
        'closed': -0.8,
        'shut': -1.0,
        'locked': -1.2,
        'sealed': -0.9,
        'trapped': -2.0,
        'stuck': -1.4,
        'jammed': -1.3,
        'frozen': -1.5,
        'paralyzed': -2.1,
        'immobilized': -1.9,
        'disabled': -1.8,
        'handicapped': -1.6,
        'impaired': -1.7,
        'damaged': -1.9,
        'broken': -2.1,
        'ruined': -2.4,
        'destroyed': -2.5,
        'demolished': -2.3,
        'wrecked': -2.2,
        'smashed': -2.1,
        'shattered': -2.5,
        'crushed': -2.4,
        'collapsed': -2.2,
        'fallen': -1.8,
        'dropped': -1.4,
        'lost': -1.8,
        'missing': -1.3,
        'gone': -1.5,
        'disappeared': -1.7,
        'vanished': -1.6,
        'absent': -1.2,
        'away': -0.8,
        'distant': -0.9,
        'far': -0.6,
        'remote': -0.7,
        'isolated': -2.0,
        'separated': -1.4,
        'divided': -1.2,
        'split': -1.3,
        'torn': -1.8,
        'ripped': -1.6,
        'cut': -1.2,
        'sliced': -1.1,
        'chopped': -1.0,
        'carved': -0.5,
        'sculpted': 0.3,
        'shaped': 0.2,
        'formed': 0.1,
        'created': 0.6,
        'made': 0.2,
        'built': 0.4,
        'constructed': 0.3,
        'assembled': 0.2,
        'manufactured': 0.1,
        'produced': 0.2,
        'generated': 0.1,
        'developed': 0.7,
        'designed': 0.5,
        'planned': 0.3,
        'organized': 0.4,
        'arranged': 0.2,
        'prepared': 0.3,
        'ready': 0.4,
        'set': 0.1,
        'fixed': 0.6,
        'repaired': 0.8,
        'restored': 1.2,
        'renewed': 1.1,
        'refreshed': 1.3,
        'updated': 0.6,
        'upgraded': 0.8,
        'improved': 1.7,
        'enhanced': 1.5,
        'better': 1.4,
        'superior': 1.8,
        'excellent': 2.9,
        'perfect': 2.9,
        'ideal': 2.2,
        'optimal': 1.6,
        'best': 2.1,
        'top': 1.8,
        'highest': 1.5,
        'maximum': 1.2,
        'peak': 1.4,
        'summit': 1.3,
        'pinnacle': 1.6,
        'apex': 1.5,
        'climax': 1.4,
        'ultimate': 1.8,
        'final': 0.5,
        'last': -0.3,
        'end': -0.8,
        'finish': -0.5,
        'conclusion': 0.2,
        'result': 0.1,
        'outcome': 0.0,
        'consequence': -0.2,
        'effect': 0.2,
        'impact': 0.7,
        'influence': 0.5,
        'power': 0.8,
        'strength': 1.5,
        'force': 0.6,
        'energy': 0.8,
        'vigor': 1.2,
        'vitality': 1.4,
        'life': 1.1,
        'living': 0.8,
        'alive': 1.3,
        'breathing': 0.5,
        'existing': 0.2,
        'being': 0.1,
        'presence': 0.3,
        'attendance': 0.2,
        'participation': 0.6,
        'involvement': 0.5,
        'engagement': 0.8,
        'interaction': 0.4,
        'communication': 0.5,
        'conversation': 0.3,
        'discussion': 0.3,
        'debate': 0.2,
        'argument': -0.3,
        'fight': -1.8,
        'conflict': -1.3,
        'war': -2.5,
        'battle': -1.9,
        'struggle': -0.8,
        'effort': 0.8,
        'work': 0.2,
        'job': 0.1,
        'task': 0.0,
        'duty': 0.4,
        'responsibility': 0.6,
        'obligation': 0.2,
        'commitment': 1.2,
        'promise': 0.8,
        'pledge': 0.9,
        'vow': 1.0,
        'oath': 0.8,
        'word': 0.3,
        'statement': 0.2,
        'declaration': 0.4,
        'announcement': 0.2,
        'news': 0.1,
        'information': 0.4,
        'data': 0.2,
        'facts': 0.8,
        'truth': 1.2,
        'reality': 0.3,
        'actuality': 0.2,
        'certainty': 0.9,
        'surety': 0.8,
        'confidence': 1.4,
        'assurance': 1.0,
        'guarantee': 1.1,
        'security': 1.4,
        'safety': 1.5,
        'protection': 1.6,
        'defense': 1.2,
        'shield': 1.1,
        'guard': 0.9,
        'watch': 0.3,
        'care': 1.2,
        'attention': 0.3,
        'focus': 0.5,
        'concentration': 0.4,
        'dedication': 1.2,
        'devotion': 1.6,
        'loyalty': 1.4,
        'faithfulness': 1.5,
        'trust': 1.6,
        'belief': 0.7,
        'faith': 1.3,
        'hope': 1.8,
        'optimism': 1.7,
        'positivity': 1.9,
        'enthusiasm': 1.8,
        'excitement': 1.9,
        'joy': 2.2,
        'happiness': 2.4,
        'pleasure': 1.8,
        'delight': 2.2,
        'satisfaction': 1.6,
        'contentment': 1.4,
        'peace': 1.8,
        'calm': 1.4,
        'serenity': 1.6,
        'tranquility': 1.5,
        'quiet': 0.8,
        'silence': 0.5,
        'stillness': 0.6,
        'rest': 1.0,
        'relaxation': 1.5,
        'comfort': 1.2,
        'ease': 1.3,
        'convenience': 1.5,
        'luxury': 1.5,
        'wealth': 1.2,
        'riches': 1.1,
        'fortune': 0.4,
        'money': 0.3,
        'cash': 0.2,
        'income': 0.4,
        'salary': 0.3,
        'wage': 0.2,
        'pay': 0.1,
        'payment': -0.3,
        'cost': -0.6,
        'expense': -0.9,
        'spending': -0.7,
        'purchase': -0.2,
        'buy': -0.1,
        'sell': 0.0,
        'trade': 0.1,
        'exchange': 0.2,
        'swap': 0.1,
        'change': 0.2,
        'switch': 0.1,
        'shift': 0.0,
        'move': 0.2,
        'transfer': 0.1,
        'transport': 0.0,
        'carry': 0.1,
        'bring': 0.3,
        'take': 0.0,
        'get': 0.2,
        'obtain': 0.4,
        'acquire': 0.3,
        'gain': 0.6,
        'earn': 0.8,
        'win': 1.9,
        'achieve': 1.9,
        'accomplish': 1.9,
        'succeed': 2.0,
        'triumph': 2.1,
        'victory': 2.0,
        'success': 1.9,
        'winner': 1.8,
        'champion': 2.0,
        'hero': 1.9,
        'star': 1.6,
        'celebrity': 1.2,
        'famous': 1.3,
        'popular': 1.2,
        'well-known': 1.1,
        'recognized': 1.3,
        'acknowledged': 1.1,
        'respected': 1.5,
        'admired': 1.7,
        'loved': 2.2,
        'adored': 2.1,
        'cherished': 2.0,
        'treasured': 1.9,
        'valued': 1.7,
        'appreciated': 1.7,
        'grateful': 1.9,
        'thankful': 1.8,
        'blessed': 2.0,
        'fortunate': 1.6,
        'lucky': 0.2,
        'chance': 0.3,
        'opportunity': 0.8,
        'possibility': 0.4,
        'potential': 0.6,
        'capability': 0.8,
        'ability': 0.9,
        'skill': 1.4,
        'talent': 1.7,
        'gift': 1.8,
        'genius': 2.4,
        'brilliance': 2.6,
        'intelligence': 1.4,
        'wisdom': 1.6,
        'knowledge': 0.8,
        'understanding': 0.9,
        'comprehension': 0.7,
        'awareness': 0.7,
        'consciousness': 0.6,
        'mindfulness': 0.8,
        'attention': 0.3,
        'focus': 0.5,
        'concentration': 0.4,
        'meditation': 1.2,
        'reflection': 0.8,
        'thought': 0.0,
        'thinking': 0.1,
        'consideration': 0.2,
        'contemplation': 0.4,
        'pondering': 0.3,
        'wondering': 0.2,
        'curiosity': 0.6,
        'interest': 0.5,
        'fascination': 1.2,
        'attraction': 0.8,
        'appeal': 0.7,
        'charm': 1.6,
        'beauty': 2.3,
        'elegance': 1.6,
        'grace': 1.7,
        'style': 1.4,
        'fashion': 1.2,
        'trend': 1.3,
        'popularity': 1.2,
        'fame': 1.3,
        'reputation': 1.1,
        'status': 0.8,
        'position': 0.5,
        'rank': 0.6,
        'level': 0.3,
        'degree': 0.2,
        'extent': 0.1,
        'amount': 0.0,
        'quantity': 0.0,
        'number': 0.0,
        'count': 0.0,
        'total': 0.1,
        'sum': 0.0,
        'whole': 0.2,
        'complete': 0.5,
        'full': 0.3,
        'entire': 0.2,
        'all': 0.1,
        'every': 0.0,
        'each': 0.0,
        'individual': 0.1,
        'single': -0.3,
        'one': 0.0,
        'first': 0.4,
        'primary': 0.5,
        'main': 0.3,
        'principal': 0.4,
        'chief': 0.5,
        'head': 0.3,
        'leader': 1.6,
        'boss': 0.8,
        'manager': 0.6,
        'director': 0.7,
        'executive': 0.8,
        'officer': 0.5,
        'official': 0.4,
        'authority': 0.6,
        'power': 0.8,
        'control': 0.3,
        'command': 0.5,
        'order': 0.2,
        'instruction': 0.1,
        'direction': 0.2,
        'guidance': 0.8,
        'advice': 0.6,
        'suggestion': 0.4,
        'recommendation': 0.5,
        'proposal': 0.3,
        'idea': 0.4,
        'concept': 0.3,
        'notion': 0.2,
        'thought': 0.0,
        'opinion': 0.1,
        'view': 0.1,
        'perspective': 0.2,
        'viewpoint': 0.1,
        'standpoint': 0.1,
        'position': 0.5,
        'stance': 0.3,
        'attitude': 0.2,
        'approach': 0.3,
        'method': 0.2,
        'way': 0.1,
        'manner': 0.1,
        'style': 1.4,
        'technique': 0.4,
        'strategy': 1.4,
        'plan': 0.3,
        'scheme': -0.2,
        'program': 0.2,
        'project': 0.4,
        'initiative': 1.8,
        'campaign': 0.6,
        'movement': 0.5,
        'action': 1.0,
        'activity': 0.4,
        'operation': 0.3,
        'function': 0.2,
        'process': 0.1,
        'procedure': 0.0,
        'system': 0.2,
        'structure': 0.1,
        'organization': 0.4,
        'institution': 0.3,
        'establishment': 0.2,
        'company': 0.1,
        'business': 0.2,
        'enterprise': 0.4,
        'venture': 0.5,
        'startup': 0.6,
        'firm': 0.2,
        'corporation': 0.1,
        'agency': 0.2,
        'bureau': 0.1,
        'department': 0.1,
        'division': 0.0,
        'section': 0.0,
        'unit': 0.0,
        'group': 0.2,
        'team': 0.5,
        'crew': 0.4,
        'staff': 0.3,
        'personnel': 0.2,
        'workforce': 0.3,
        'employees': 0.2,
        'workers': 0.1,
        'people': 0.3,
        'individuals': 0.1,
        'persons': 0.0,
        'humans': 0.2,
        'beings': 0.1,
        'creatures': 0.0,
        'animals': 0.1,
        'pets': 0.8,
        'companions': 1.2,
        'friends': 1.7,
        'buddies': 1.5,
        'pals': 1.4,
        'mates': 1.3,
        'partners': 1.3,
        'colleagues': 0.8,
        'coworkers': 0.6,
        'associates': 0.5,
        'allies': 1.2,
        'supporters': 1.4,
        'fans': 1.2,
        'followers': 0.8,
        'admirers': 1.3,
        'lovers': 2.2,
        'family': 1.7,
        'relatives': 0.8,
        'parents': 1.1,
        'children': 1.4,
        'kids': 1.3,
        'siblings': 0.9,
        'spouse': 1.2,
        'husband': 1.0,
        'wife': 1.0,
        'partner': 1.3,
        'boyfriend': 1.1,
        'girlfriend': 1.1,
        'relationship': 0.5,
        'marriage': 1.2,
        'wedding': 1.8,
        'engagement': 1.6,
        'proposal': 1.4,
        'romance': 1.8,
        'love': 2.2,
        'affection': 1.9,
        'care': 1.2,
        'concern': -0.5,
        'worry': -1.2,
        'anxiety': -1.6,
        'stress': -1.4,
        'pressure': -0.8,
        'tension': -1.0,
        'strain': -1.1,
        'burden': -1.4,
        'load': -0.9,
        'weight': -0.7,
        'heavy': -0.8,
        'light': 0.6,
        'easy': 1.3,
        'simple': 1.2,
        'basic': 0.8,
        'elementary': 0.6,
        'fundamental': 0.7,
        'essential': 1.1,
        'important': 1.2,
        'significant': 1.5,
        'meaningful': 1.6,
        'valuable': 1.7,
        'precious': 1.9,
        'priceless': 2.1,
        'invaluable': 2.0,
        'worthwhile': 1.5,
        'beneficial': 1.8,
        'helpful': 1.6,
        'useful': 1.4,
        'practical': 1.3,
        'functional': 1.2,
        'effective': 1.5,
        'efficient': 1.5,
        'productive': 1.7,
        'successful': 2.0,
        'victorious': 2.1,
        'triumphant': 2.2,
        'winning': 1.9,
        'champion': 2.0,
        'winner': 1.8,
        'hero': 1.9,
        'star': 1.6,
        'celebrity': 1.2,
        'famous': 1.3,
        'popular': 1.2,
        'well-known': 1.1,
        'recognized': 1.3,
        'acknowledged': 1.1,
        'respected': 1.5,
        'admired': 1.7,
        'loved': 2.2,
        'adored': 2.1,
        'cherished': 2.0,
        'treasured': 1.9,
        'valued': 1.7,
        'appreciated': 1.7,
        'grateful': 1.9,
        'thankful': 1.8,
        'blessed': 2.0,
        'fortunate': 1.6,
        'lucky': 0.2,

        // Negative Indian slang
        'bakwas': -2.1,
        'faltu': -1.8,
        'bekar': -1.9,
        'ghatiya': -2.3,
        'kharab': -1.7,
        'bura': -1.5,
        'mid': -1.2,
        'trash': -2.0,
        'cringe': -1.8,
        'sus': -1.3,
        'cap': -1.5, // lie
        'ratio': -1.4,
        'flop': -1.9,
        'dead': -1.6,
        'boring': -1.4,
        'meh': -0.8,
        'nah': -1.1,
        'bruh': -0.9,
        'oof': -1.2,
        'yikes': -1.7,

        // Political/Policy context
        'policy': 0.5,
        'policies': 0.5,
        'government': 0.0,
        'minister': 0.0,
        'parliament': 0.2,
        'constitution': 0.8,
        'democracy': 1.2,
        'rights': 1.5,
        'justice': 1.8,
        'corruption': -2.5,
        'scam': -2.8,
        'protest': -0.5,
        'revolution': 1.0,
        'reform': 1.3,
        'development': 1.6,
        'progress': 1.8,
        'backward': -1.5,
        'failure': -2.0,
        'transparency': 1.7,
        'accountability': 1.6,
        'efficiency': 1.5,
        'innovation': 1.8,
        'sustainability': 1.6,
        'sustainable': 1.6,
        'equality': 1.9,
        'fairness': 1.8,
        'inclusion': 1.7,
        'diversity': 1.4,
        'opportunity': 1.6,
        'prosperity': 1.9,
        'welfare': 1.5,
        'security': 1.4,
        'stability': 1.3,
        'growth': 1.6,
        'improvement': 1.5,
        'advancement': 1.6,
        'achievement': 1.7,
        'success': 1.9,
        'victory': 2.0,
        'triumph': 2.1,
        'breakthrough': 2.2,
        'milestone': 1.8,
        'accomplishment': 1.9,

        // Environmental/Green Economy words
        'green': 1.5,
        'eco': 1.4,
        'eco-friendly': 1.8,
        'environment': 1.2,
        'environmental': 1.2,
        'climate': 0.8,
        'carbon': 0.3,
        'footprint': 0.2,
        'emissions': 0.1,
        'renewable': 1.6,
        'clean': 1.4,
        'energy': 0.8,
        'solar': 1.2,
        'wind': 1.1,
        'conservation': 1.5,
        'preserve': 1.4,
        'protect': 1.6,
        'protection': 1.6,
        'economy': 0.5,
        'economic': 0.3,
        'initiative': 1.6,
        'measure': 0.8,
        'measures': 0.8,
        'action': 1.0,
        'actions': 1.0,
        'taken': 0.5,
        'implement': 1.2,
        'implementation': 1.2,
        'adopt': 1.1,
        'adoption': 1.1,
    }

    // Advanced pattern-based sentiment detection for statements without explicit keywords
    private sentimentPatterns = {
        // Positive patterns - detect constructive, supportive language
        positive: [
            /\b(should|must|need to|have to)\s+(improve|fix|change|address|solve|enhance|develop)\b/gi,
            /\b(i\s+)?(agree|support|endorse|back|favor|approve)\b/gi,
            /\b(this\s+)?(makes sense|is logical|is reasonable|is fair|is right|is correct)\b/gi,
            /\b(good\s+)?(point|idea|suggestion|proposal|solution|approach|strategy)\b/gi,
            /\b(thank you|thanks|appreciate|grateful|kudos|props)\b/gi,
            /\b(well done|great job|nice work|good effort|impressive work)\b/gi,
            /\b(i\s+)?(like|love|enjoy|prefer|admire)\s+(this|it|that)\b/gi,
            /\b(finally|at last|about time|glad to see)\b/gi,
            /\b(exactly|precisely|absolutely|definitely|certainly|totally)\b/gi,
            /\b(hope|wish|want|desire)\s+(this|it)\s+(works|succeeds|happens|passes)\b/gi,
            /\b(looking forward|excited about|optimistic about)\b/gi,
            /\b(step in the right direction|positive development|welcome change)\b/gi,

            // Enhanced positive step/action patterns
            /\b(very\s+)?(positive|good|great|excellent|wonderful)\s+(step|move|decision|action|initiative|policy|approach)\b/gi,
            /\b(i\s+think\s+this\s+is\s+)?(a\s+)?(very\s+)?(positive|good|great|excellent|beneficial|helpful)\b/gi,
            /\b(taken\s+by\s+)?(government|administration|authorities)\s+to\s+(reduce|improve|enhance|promote|advance)\b/gi,
            /\b(promote|promoting|promotes)\s+(green|sustainable|clean|renewable|eco-friendly)\b/gi,
            /\b(reduce|reducing|reduces)\s+(carbon|pollution|emissions|waste|footprint)\b/gi,
            /\b(green\s+)?(economy|energy|technology|solutions|initiatives|policies)\b/gi,
            /\b(sustainable\s+)?(development|growth|future|practices|solutions)\b/gi,
            /\b(environmental\s+)?(protection|conservation|sustainability|benefits|improvements)\b/gi,
            /\b(climate\s+)?(action|protection|solutions|initiatives|policies)\b/gi,
            /\b(renewable\s+)?(energy|resources|power|solutions)\b/gi,
            /\b(i\s+)?(support|endorse|back|favor|appreciate)\s+(this|these|such)\s+(steps|measures|policies|initiatives)\b/gi,
            /\b(this\s+will\s+)?(help|benefit|improve|enhance|advance|promote)\b/gi,
            /\b(move\s+)?(towards|toward)\s+(sustainability|green|clean|renewable)\b/gi,

            // SDG and International Compliance Patterns
            /\b(initiative|policy|measure|action|step)\s+(by\s+)?(the\s+)?government\s+(ensures|guarantees|helps|enables)\b/gi,
            /\b(ensures|guarantees|helps|enables)\s+(that\s+)?(the\s+)?country\s+(meets|achieves|fulfills|attains)\b/gi,
            /\b(meets|achieves|fulfills|attains|reaches)\s+(sdg|sustainable\s+development)\s+goals\b/gi,
            /\b(complies\s+with|adheres\s+to|follows|observes|respects)\s+(international|global|worldwide)\s+(rules|regulations|standards|norms|guidelines)\b/gi,
            /\b(international\s+)?(rules|regulations|standards|norms|guidelines|laws|treaties|agreements|conventions|protocols)\b/gi,
            /\b(hence|therefore|thus|consequently|as\s+a\s+result)\s+(the\s+)?(initiative|policy|measure|action|step)\s+(is\s+)?(commendable|praiseworthy|laudable|admirable|excellent|good)\b/gi,
            /\b(commendable|praiseworthy|laudable|admirable|excellent|good|positive)\s+(initiative|policy|measure|action|step|effort|work|approach)\b/gi,
            /\b(government\s+)?(initiative|policy|measure|action|step)\s+(is\s+)?(commendable|praiseworthy|laudable|admirable|excellent|good|positive|beneficial|helpful)\b/gi,
            /\b(this\s+)?(ensures|guarantees|secures|safeguards|protects)\s+(compliance|adherence|conformity)\b/gi,
            /\b(compliance\s+with|adherence\s+to)\s+(international|global|worldwide)\b/gi,
            /\b(sustainable\s+development\s+goals|sdg\s+goals|millennium\s+development\s+goals)\b/gi,
            /\b(environmental\s+)?(compliance|standards|regulations|guidelines|protocols)\b/gi,
            /\b(climate\s+)?(compliance|commitments|targets|goals|objectives)\b/gi,
            /\b(paris\s+agreement|kyoto\s+protocol|cop\d+|unfccc)\b/gi,
            /\b(un\s+)?(sustainable\s+development|millennium\s+development|climate\s+action)\b/gi,
            /\b(global\s+)?(goals|targets|objectives|commitments|standards)\b/gi,
            /\b(international\s+)?(cooperation|collaboration|partnership|alliance)\b/gi,
            /\b(multilateral\s+)?(agreement|treaty|accord|pact|convention)\b/gi,
            /\b(framework\s+)?(convention|agreement|protocol|treaty)\b/gi,
            /\b(binding\s+)?(commitments|obligations|targets|goals)\b/gi,
            /\b(voluntary\s+)?(commitments|targets|goals|initiatives)\b/gi,
            /\b(nationally\s+determined\s+contributions|ndcs)\b/gi,
            /\b(carbon\s+)?(neutrality|neutral|zero|negative)\b/gi,
            /\b(net\s+zero|carbon\s+free|emission\s+free)\b/gi,
            /\b(renewable\s+energy\s+)?(targets|goals|commitments)\b/gi,
            /\b(energy\s+)?(efficiency|conservation|transition)\b/gi,
            /\b(circular\s+economy|green\s+economy|low\s+carbon\s+economy)\b/gi,
            /\b(sustainable\s+)?(finance|investment|funding|financing)\b/gi,
            /\b(green\s+)?(bonds|finance|investment|funding|technology)\b/gi,
            /\b(climate\s+)?(finance|funding|investment|adaptation|mitigation)\b/gi,
            /\b(environmental\s+)?(impact|assessment|monitoring|reporting)\b/gi,
            /\b(transparency\s+)?(reporting|disclosure|accountability)\b/gi,
            /\b(monitoring\s+)?(reporting|verification|mrv)\b/gi,
            /\b(peer\s+review|international\s+review|expert\s+review)\b/gi,
            /\b(compliance\s+)?(mechanism|system|framework|procedure)\b/gi,
            /\b(enforcement\s+)?(mechanism|system|procedure|measures)\b/gi,
            /\b(dispute\s+)?(resolution|settlement|mechanism)\b/gi,
            /\b(technical\s+)?(assistance|cooperation|support|transfer)\b/gi,
            /\b(capacity\s+)?(building|development|strengthening|enhancement)\b/gi,
            /\b(technology\s+)?(transfer|sharing|cooperation|development)\b/gi,
            /\b(knowledge\s+)?(sharing|transfer|exchange|dissemination)\b/gi,
            /\b(best\s+)?(practices|approaches|methods|techniques)\b/gi,
            /\b(lessons\s+)?(learned|learnt|from\s+experience)\b/gi,
            /\b(success\s+)?(stories|cases|examples|models)\b/gi,
            /\b(pilot\s+)?(projects|programs|initiatives|schemes)\b/gi,
            /\b(demonstration\s+)?(projects|programs|initiatives)\b/gi,
            /\b(scaling\s+up|scaling\s+out|replication|mainstreaming)\b/gi,
            /\b(institutional\s+)?(strengthening|development|capacity)\b/gi,
            /\b(policy\s+)?(coherence|integration|coordination|alignment)\b/gi,
            /\b(cross\s+sectoral|inter\s+sectoral|multi\s+sectoral)\b/gi,
            /\b(whole\s+of\s+government|all\s+of\s+government)\b/gi,
            /\b(stakeholder\s+)?(engagement|participation|involvement|consultation)\b/gi,
            /\b(public\s+)?(participation|engagement|consultation|involvement)\b/gi,
            /\b(civil\s+society|non\s+governmental|private\s+sector)\s+(engagement|participation|involvement)\b/gi,
            /\b(multi\s+stakeholder|inclusive|participatory)\s+(approach|process|mechanism)\b/gi,

            // === COMPREHENSIVE REAL-WORLD PATTERNS ===

            // Technology & Innovation Positive Patterns
            /\b(this\s+)?(is\s+)?(a\s+)?(game\s+changer|breakthrough|revolutionary|innovative|cutting-edge)\b/gi,
            /\b(finally\s+)?(a\s+)?(solution|fix|answer|breakthrough)\s+(to|for)\b/gi,
            /\b(works\s+)?(perfectly|flawlessly|seamlessly|smoothly|great|well)\b/gi,
            /\b(love\s+)?(this\s+)?(app|software|technology|innovation|feature|update)\b/gi,
            /\b(makes\s+)?(life|work|things)\s+(easier|better|simpler|more\s+convenient)\b/gi,
            /\b(saves\s+)?(time|money|effort|energy|resources)\b/gi,
            /\b(highly\s+)?(recommend|suggest|endorse)\s+(this|it)\b/gi,
            /\b(user\s+friendly|easy\s+to\s+use|intuitive|straightforward)\b/gi,
            /\b(fast|quick|speedy|rapid|instant|immediate)\s+(and\s+)?(reliable|efficient|effective)\b/gi,
            /\b(secure|safe|protected|encrypted|private)\s+(and\s+)?(reliable|trustworthy)\b/gi,

            // Social & Cultural Positive Patterns
            /\b(proud\s+)?(to\s+)?(be|live|work|study)\s+(in|at|with)\b/gi,
            /\b(great\s+)?(community|neighborhood|city|country|culture|tradition)\b/gi,
            /\b(love\s+)?(the\s+)?(diversity|culture|people|community|atmosphere|vibe)\b/gi,
            /\b(feel\s+)?(welcome|accepted|included|valued|respected|appreciated)\b/gi,
            /\b(brings\s+)?(people\s+)?(together|unity|harmony|peace)\b/gi,
            /\b(celebrates|embraces|promotes|encourages)\s+(diversity|inclusion|equality|unity)\b/gi,
            /\b(breaking\s+)?(barriers|stereotypes|prejudices|discrimination)\b/gi,
            /\b(positive\s+)?(change|impact|influence|effect)\s+(in|on|for)\s+(society|community)\b/gi,

            // Economic & Business Positive Patterns
            /\b(great\s+)?(value|deal|price|offer|bargain)\s+(for\s+)?(money|price)\b/gi,
            /\b(worth\s+)?(every\s+)?(penny|dollar|rupee|cent)\b/gi,
            /\b(excellent\s+)?(customer\s+)?(service|support|experience|satisfaction)\b/gi,
            /\b(highly\s+)?(profitable|successful|effective|efficient|productive)\b/gi,
            /\b(business\s+is\s+)?(booming|thriving|growing|expanding|flourishing)\b/gi,
            /\b(economy\s+is\s+)?(recovering|improving|growing|stabilizing|strengthening)\b/gi,
            /\b(job\s+)?(market|opportunities|growth|creation|security)\s+(is\s+)?(improving|growing|expanding)\b/gi,
            /\b(investment\s+)?(returns|profits|gains|yields)\s+(are\s+)?(good|great|excellent|impressive)\b/gi,

            // Health & Wellness Positive Patterns
            /\b(feel|feeling)\s+(much\s+)?(better|healthier|stronger|fitter|energetic|vibrant)\b/gi,
            /\b(fully\s+)?(recovered|healed|cured|treated|better)\s+(from|after)\b/gi,
            /\b(great\s+)?(results|improvement|progress|recovery)\s+(from|with|after)\b/gi,
            /\b(highly\s+)?(effective|successful)\s+(treatment|therapy|medicine|cure|remedy)\b/gi,
            /\b(life\s+)?(changing|saving|improving)\s+(treatment|therapy|medicine|surgery)\b/gi,
            /\b(mental\s+)?(health|wellbeing|wellness)\s+(is\s+)?(improving|better|good|excellent)\b/gi,
            /\b(stress\s+)?(free|relief|reduction|management)\s+(and\s+)?(relaxation|peace|calm)\b/gi,

            // Education & Learning Positive Patterns
            /\b(learned\s+)?(so\s+)?(much|a\s+lot)\s+(from|about|in)\b/gi,
            /\b(excellent\s+)?(teacher|instructor|professor|mentor|guide|education|course|program)\b/gi,
            /\b(gained\s+)?(valuable|useful|practical|important)\s+(knowledge|skills|experience|insights)\b/gi,
            /\b(eye\s+opening|enlightening|educational|informative|insightful)\s+(experience|course|program|book)\b/gi,
            /\b(highly\s+)?(recommend|suggest)\s+(this\s+)?(course|program|book|teacher|school|university)\b/gi,
            /\b(proud\s+)?(of\s+)?(my|our)\s+(achievement|graduation|degree|certification|accomplishment)\b/gi,

            // Entertainment & Leisure Positive Patterns
            /\b(absolutely\s+)?(loved|enjoyed|adored)\s+(this|it|the)\s+(movie|show|book|game|song|album)\b/gi,
            /\b(can't\s+)?(stop\s+)?(watching|reading|playing|listening)\s+(to\s+)?(this|it)\b/gi,
            /\b(best\s+)?(movie|show|book|game|song|album)\s+(i've\s+)?(ever\s+)?(seen|watched|read|played|heard)\b/gi,
            /\b(masterpiece|classic|brilliant|genius|incredible|amazing)\s+(work|performance|acting|direction)\b/gi,
            /\b(had\s+)?(such\s+)?(a\s+)?(great|wonderful|amazing|fantastic)\s+(time|experience|day|night|vacation)\b/gi,
            /\b(beautiful\s+)?(scenery|landscape|view|place|location|destination)\b/gi,

            // Personal Relationships Positive Patterns
            /\b(so\s+)?(grateful|thankful|blessed)\s+(for|to\s+have)\s+(my|our|such)\b/gi,
            /\b(lucky\s+)?(to\s+)?(have|find|meet)\s+(such\s+)?(amazing|wonderful|great|loving|caring)\b/gi,
            /\b(best\s+)?(friend|partner|husband|wife|family|parents|children)\s+(ever|in\s+the\s+world)\b/gi,
            /\b(love\s+)?(spending\s+)?(time|moments)\s+(with|together)\b/gi,
            /\b(strong\s+)?(bond|relationship|connection|friendship|marriage|family)\b/gi,
            /\b(support\s+)?(each\s+)?(other|one\s+another)\s+(through|in|during)\b/gi,

            // Food & Lifestyle Positive Patterns
            /\b(absolutely\s+)?(delicious|tasty|yummy|scrumptious|mouth-watering|amazing)\s+(food|meal|dish|cuisine)\b/gi,
            /\b(best\s+)?(restaurant|cafe|food|meal|dish)\s+(in\s+)?(town|the\s+city|the\s+area)\b/gi,
            /\b(highly\s+)?(recommend|suggest)\s+(this\s+)?(restaurant|cafe|dish|place|recipe)\b/gi,
            /\b(fresh|organic|natural|healthy|nutritious)\s+(and\s+)?(delicious|tasty|flavorful)\b/gi,
            /\b(love\s+)?(the\s+)?(atmosphere|ambiance|vibe|decor|service|staff)\b/gi,
            /\b(perfect\s+)?(for\s+)?(date\s+night|family\s+dinner|celebration|special\s+occasion)\b/gi,
        ],

        // Negative patterns - detect criticism, opposition, concern
        negative: [
            /\b(i\s+)?(disagree|oppose|reject|refuse|deny|object)\b/gi,
            /\b(this\s+)?(doesn't work|won't work|is broken|is wrong|is unfair|is flawed)\b/gi,
            /\b(what\s+a\s+)?(waste|joke|disaster|mess|failure|shame|disappointment)\b/gi,
            /\b(i\s+)?(hate|dislike|can't stand|despise|loathe)\b/gi,
            /\b(never|not|no way|absolutely not|definitely not|impossible)\b/gi,
            /\b(unfortunately|sadly|regrettably|disappointingly)\b/gi,
            /\b(worried|concerned|afraid|scared|anxious|nervous)\s+(about|that|of)\b/gi,
            /\b(this\s+is\s+)?(ridiculous|absurd|nonsense|stupid|idiotic|crazy)\b/gi,
            /\b(fed up|sick of|tired of|had enough|can't take)\b/gi,
            /\b(doubt|question|suspect|skeptical)\s+(this|it|that|whether)\b/gi,
            /\b(makes no sense|doesn't add up|fishy|suspicious)\b/gi,
            /\b(step backward|going backwards|regression|decline)\b/gi,

            // === COMPREHENSIVE NEGATIVE PATTERNS ===

            // Technology & Innovation Negative Patterns
            /\b(this\s+)?(app|software|technology|system|device)\s+(is\s+)?(terrible|awful|horrible|useless|broken|buggy)\b/gi,
            /\b(constantly\s+)?(crashes|freezes|lags|glitches|fails|breaks)\b/gi,
            /\b(waste\s+of\s+)?(time|money|effort|resources)\b/gi,
            /\b(don't\s+)?(recommend|suggest|advise|endorse)\s+(this|it)\b/gi,
            /\b(avoid\s+)?(this|it)\s+(at\s+all\s+costs|like\s+the\s+plague)\b/gi,
            /\b(outdated|obsolete|ancient|primitive|backward)\s+(technology|system|approach)\b/gi,
            /\b(poor|bad|terrible|awful)\s+(design|interface|user\s+experience|functionality)\b/gi,
            /\b(security\s+)?(issues|problems|vulnerabilities|breaches|risks)\b/gi,
            /\b(privacy\s+)?(concerns|issues|violations|breaches)\b/gi,
            /\b(data\s+)?(loss|theft|breach|leak|corruption)\b/gi,

            // Social & Cultural Negative Patterns
            /\b(discrimination|prejudice|racism|sexism|bias)\s+(against|towards)\b/gi,
            /\b(feel\s+)?(unwelcome|excluded|rejected|discriminated|marginalized|oppressed)\b/gi,
            /\b(toxic\s+)?(culture|environment|atmosphere|community|workplace)\b/gi,
            /\b(lack\s+of\s+)?(diversity|inclusion|equality|representation|tolerance)\b/gi,
            /\b(social\s+)?(injustice|inequality|discrimination|oppression|exploitation)\b/gi,
            /\b(cultural\s+)?(appropriation|insensitivity|ignorance|stereotypes)\b/gi,
            /\b(hate\s+)?(speech|crime|groups|comments|messages)\b/gi,
            /\b(bullying|harassment|intimidation|abuse|violence)\b/gi,

            // Economic & Business Negative Patterns
            /\b(overpriced|expensive|costly|unaffordable|rip-off|scam)\b/gi,
            /\b(poor\s+)?(quality|service|customer\s+service|support|experience)\b/gi,
            /\b(terrible\s+)?(customer\s+)?(service|support|experience|treatment)\b/gi,
            /\b(business\s+is\s+)?(failing|struggling|declining|collapsing|bankrupt)\b/gi,
            /\b(economy\s+is\s+)?(crashing|declining|failing|in\s+recession|struggling)\b/gi,
            /\b(job\s+)?(losses|cuts|layoffs|unemployment|insecurity)\b/gi,
            /\b(financial\s+)?(crisis|problems|difficulties|struggles|hardship)\b/gi,
            /\b(lost\s+)?(money|investment|savings|job|income)\b/gi,
            /\b(can't\s+)?(afford|pay\s+for|buy|purchase)\b/gi,

            // Health & Wellness Negative Patterns
            /\b(feel|feeling)\s+(terrible|awful|sick|unwell|worse|pain)\b/gi,
            /\b(health\s+)?(problems|issues|concerns|complications|deteriorating)\b/gi,
            /\b(side\s+)?(effects|reactions)\s+(from|of|caused\s+by)\b/gi,
            /\b(treatment\s+)?(failed|didn't\s+work|ineffective|unsuccessful)\b/gi,
            /\b(mental\s+)?(health\s+)?(crisis|breakdown|depression|anxiety|stress)\b/gi,
            /\b(chronic\s+)?(pain|illness|disease|condition|suffering)\b/gi,
            /\b(can't\s+)?(sleep|eat|function|work|concentrate)\b/gi,
            /\b(exhausted|drained|burned\s+out|overwhelmed|stressed)\b/gi,

            // Education & Learning Negative Patterns
            /\b(terrible\s+)?(teacher|instructor|professor|education|course|school)\b/gi,
            /\b(waste\s+of\s+)?(time|money)\s+(and\s+)?(effort|energy)\b/gi,
            /\b(learned\s+)?(nothing|very\s+little)\s+(from|in)\b/gi,
            /\b(poor\s+)?(quality\s+)?(education|teaching|instruction|curriculum)\b/gi,
            /\b(outdated\s+)?(curriculum|syllabus|methods|approach|materials)\b/gi,
            /\b(failed\s+)?(exam|test|course|grade|assignment)\b/gi,
            /\b(struggling\s+)?(with|in)\s+(studies|school|college|university)\b/gi,
            /\b(can't\s+)?(understand|grasp|learn|remember|focus)\b/gi,

            // Entertainment & Leisure Negative Patterns
            /\b(worst\s+)?(movie|show|book|game|song|album)\s+(ever|i've\s+ever\s+seen)\b/gi,
            /\b(waste\s+of\s+)?(time|money)\s+(watching|reading|playing)\b/gi,
            /\b(boring|dull|tedious|monotonous|uninteresting|bland)\s+(movie|show|book|game)\b/gi,
            /\b(terrible\s+)?(acting|direction|plot|story|graphics|music)\b/gi,
            /\b(couldn't\s+)?(finish|complete|sit\s+through)\s+(watching|reading|playing)\b/gi,
            /\b(fell\s+asleep|dozed\s+off)\s+(during|while\s+watching)\b/gi,
            /\b(ruined\s+)?(vacation|holiday|trip|experience|day|night)\b/gi,

            // Personal Relationships Negative Patterns
            /\b(relationship\s+)?(problems|issues|troubles|difficulties|crisis)\b/gi,
            /\b(fight|argument|conflict|disagreement)\s+(with|between)\b/gi,
            /\b(feel\s+)?(lonely|isolated|abandoned|rejected|unloved|unwanted)\b/gi,
            /\b(toxic\s+)?(relationship|friendship|family|partner|spouse)\b/gi,
            /\b(abuse|violence|harassment|manipulation|control)\s+(in|from)\b/gi,
            /\b(trust\s+)?(issues|problems|broken|lost|betrayed)\b/gi,
            /\b(going\s+through\s+)?(divorce|separation|breakup|split)\b/gi,
            /\b(can't\s+)?(trust|rely\s+on|depend\s+on|count\s+on)\b/gi,

            // Food & Lifestyle Negative Patterns
            /\b(terrible\s+)?(food|meal|service|restaurant|experience)\b/gi,
            /\b(worst\s+)?(restaurant|food|meal|service)\s+(ever|i've\s+ever\s+had)\b/gi,
            /\b(food\s+)?(poisoning|contamination|spoiled|rotten|stale)\b/gi,
            /\b(poor\s+)?(hygiene|cleanliness|sanitation|conditions)\b/gi,
            /\b(overpriced|expensive)\s+(for\s+)?(such\s+)?(poor|bad|terrible)\s+(quality|food|service)\b/gi,
            /\b(rude\s+)?(staff|waiters|service|management|owner)\b/gi,
            /\b(long\s+)?(wait|waiting\s+time|delay)\s+(for\s+)?(food|service|table)\b/gi,
            /\b(dirty\s+)?(restaurant|kitchen|tables|utensils|bathroom)\b/gi,
        ],

        // Intensifiers - amplify existing sentiment
        intensifiers: [
            /\b(very|extremely|incredibly|absolutely|totally|completely|utterly)\b/gi,
            /\b(quite|rather|really|truly|genuinely|seriously)\b/gi,
            /\b(so|such|too|way too|far too|overly)\b/gi,
            /\b(highly|deeply|strongly|badly|terribly|massively)\b/gi,
        ],

        // Negation patterns - flip sentiment
        negations: [
            /\b(not|no|never|nothing|nobody|nowhere|neither|nor)\b/gi,
            /\b(don't|doesn't|didn't|won't|wouldn't|can't|couldn't|shouldn't|isn't|aren't|wasn't|weren't)\b/gi,
            /\b(hardly|barely|scarcely|rarely|seldom)\b/gi,
        ],

        // Sarcasm indicators - often flip positive words to negative
        sarcasm: [
            /\b(oh\s+)?(great|wonderful|fantastic|perfect|brilliant)\s*[.!]*\s*$/gi,
            /\b(sure|right|yeah right|of course)\s*[.!]*\s*$/gi,
            /\b(just\s+)?(perfect|great|wonderful|brilliant)\b/gi,
            /\b(real\s+)?(smart|clever|genius)\b/gi,
        ],

        // Uncertainty patterns - often indicate neutral to slightly negative sentiment
        uncertainty: [
            /\b(maybe|perhaps|possibly|might|could be|not sure|uncertain)\b/gi,
            /\b(i think|i believe|i guess|i suppose|seems like)\b/gi,
            /\b(kind of|sort of|somewhat|a bit|a little)\b/gi,
        ],

        // Emotional expressions without explicit sentiment words
        emotional: [
            /\b(wow|whoa|omg|wtf|damn|holy)\b/gi,
            /\b(sigh|ugh|meh|hmm|huh)\b/gi,
            /\b(yay|woohoo|hurray|hooray)\b/gi,
        ]
    }

    private emojiToText: { [key: string]: string } = {
        // Happy/Positive emojis
        '😀': 'happy', '😃': 'happy', '😄': 'very happy', '😁': 'grinning',
        '😆': 'laughing', '😅': 'laughing', '🤣': 'laughing hard', '😂': 'laughing',
        '🙂': 'happy', '😊': 'happy', '😇': 'blessed', '🥰': 'love',
        '😍': 'love', '🤩': 'amazing', '😘': 'love', '😗': 'kiss',
        '☺️': 'happy', '😚': 'kiss', '😙': 'kiss', '🥲': 'happy tears',
        '😋': 'delicious', '😛': 'playful', '😜': 'playful', '🤪': 'crazy happy',
        '😝': 'playful', '🤑': 'money happy', '🤗': 'hug', '🤭': 'giggling',

        // Sad/Negative emojis
        '😕': 'sad', '🙁': 'sad', '☹️': 'sad', '😣': 'struggling',
        '😖': 'frustrated', '😫': 'tired', '😩': 'weary', '🥺': 'pleading',
        '😢': 'crying', '😭': 'crying hard', '😤': 'angry', '😠': 'angry',
        '😡': 'very angry', '🤬': 'swearing', '🤯': 'mind blown', '😳': 'shocked',
        '🥵': 'hot angry', '🥶': 'cold', '😱': 'scared', '😨': 'fearful',
        '😰': 'anxious', '😥': 'disappointed', '😓': 'stressed',

        // Neutral expressions
        '😐': 'neutral', '😑': 'neutral', '😶': 'silent', '🤔': 'thinking',
        '🤨': 'suspicious', '😏': 'smirk', '😒': 'unamused', '🙄': 'eye roll',

        // Gestures
        '👍': 'thumbs up', '👎': 'thumbs down', '👌': 'okay', '✌️': 'peace',
        '🤞': 'fingers crossed', '👏': 'clapping', '🙌': 'praise', '🙏': 'prayer',

        // Hearts and love
        '❤️': 'love', '💛': 'yellow heart', '💚': 'green heart', '💙': 'blue heart',
        '💜': 'purple heart', '🖤': 'black heart', '🤍': 'white heart', '💔': 'broken heart',

        // Fire and energy
        '🔥': 'fire', '⚡': 'lightning', '💥': 'explosion', '✨': 'sparkles',
        '🌟': 'star', '⭐': 'star', '🌈': 'rainbow', '☀️': 'sun'
    }

    private customThresholds = {
        positive: 0.01, // More sensitive to positive sentiment
        negative: -0.02
    }

    constructor() {
        this.enhanceVADERLexicon()
    }

    private enhanceVADERLexicon() {
        Object.entries(this.enhancedLexicon).forEach(([word, score]) => {
            if (vader.SentimentIntensityAnalyzer) {
                try {
                    (vader as any).lexicon = { ...(vader as any).lexicon, [word]: score }
                } catch (error) {
                    // Fallback: handle in preprocessing
                }
            }
        })
    }

    preprocessText(text: string): string {
        let processedText = text
        let sentimentBoost = 0

        // Convert emojis to text
        Object.entries(this.emojiToText).forEach(([emoji, textEquivalent]) => {
            const regex = new RegExp(emoji.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')
            processedText = processedText.replace(regex, ` ${textEquivalent} `)
        })

        // Detect sentiment patterns even without explicit keywords
        this.sentimentPatterns.positive.forEach(pattern => {
            if (pattern.test(processedText)) {
                processedText += ' positive sentiment detected'
                sentimentBoost += 0.4 // Increased boost for pattern detection
            }
        })

        // Special handling for compound positive phrases
        const compoundPositivePatterns = [
            /\b(very\s+positive\s+step)\b/gi,
            /\b(positive\s+step)\b/gi,
            /\b(good\s+step)\b/gi,
            /\b(great\s+step)\b/gi,
            /\b(reduce\s+carbon\s+footprint)\b/gi,
            /\b(promote\s+green\s+economy)\b/gi,
            /\b(environmental\s+protection)\b/gi,
            /\b(sustainable\s+development)\b/gi,
            /\b(climate\s+action)\b/gi,
            /\b(renewable\s+energy)\b/gi,
            /\b(initiative\s+by\s+the\s+government)\b/gi,
            /\b(government\s+initiative)\b/gi,
            /\b(ensures\s+that\s+the\s+country)\b/gi,
            /\b(meets\s+sdg\s+goals)\b/gi,
            /\b(sustainable\s+development\s+goals)\b/gi,
            /\b(complies\s+with\s+international)\b/gi,
            /\b(international\s+rules\s+and\s+regulations)\b/gi,
            /\b(hence\s+.*\s+commendable)\b/gi,
            /\b(therefore\s+.*\s+commendable)\b/gi,
            /\b(thus\s+.*\s+commendable)\b/gi,
            /\b(initiative\s+.*\s+commendable)\b/gi,
            /\b(government\s+.*\s+commendable)\b/gi,
            /\b(policy\s+.*\s+commendable)\b/gi,
            /\b(measure\s+.*\s+commendable)\b/gi,
            /\b(action\s+.*\s+commendable)\b/gi,
            /\b(step\s+.*\s+commendable)\b/gi,
            /\b(commendable\s+initiative)\b/gi,
            /\b(commendable\s+policy)\b/gi,
            /\b(commendable\s+measure)\b/gi,
            /\b(commendable\s+action)\b/gi,
            /\b(commendable\s+step)\b/gi,
            /\b(commendable\s+effort)\b/gi,
            /\b(commendable\s+work)\b/gi,
            /\b(commendable\s+approach)\b/gi,
            /\b(praiseworthy\s+initiative)\b/gi,
            /\b(laudable\s+initiative)\b/gi,
            /\b(admirable\s+initiative)\b/gi,
            /\b(exemplary\s+initiative)\b/gi,
            /\b(noteworthy\s+initiative)\b/gi,
            /\b(compliance\s+with\s+international)\b/gi,
            /\b(adherence\s+to\s+international)\b/gi,
            /\b(conformity\s+with\s+international)\b/gi,
            /\b(meets\s+international\s+standards)\b/gi,
            /\b(fulfills\s+international\s+obligations)\b/gi,
            /\b(satisfies\s+international\s+requirements)\b/gi,
            /\b(achieves\s+international\s+goals)\b/gi,
            /\b(attains\s+international\s+targets)\b/gi,
            /\b(realizes\s+international\s+objectives)\b/gi,
            /\b(accomplishes\s+international\s+commitments)\b/gi,
            /\b(delivers\s+on\s+international\s+promises)\b/gi,
            /\b(implements\s+international\s+agreements)\b/gi,
            /\b(executes\s+international\s+treaties)\b/gi,
            /\b(upholds\s+international\s+conventions)\b/gi,
            /\b(maintains\s+international\s+protocols)\b/gi,
            /\b(observes\s+international\s+guidelines)\b/gi,
            /\b(respects\s+international\s+norms)\b/gi,
            /\b(honors\s+international\s+commitments)\b/gi,
            /\b(abides\s+by\s+international\s+rules)\b/gi,
            /\b(follows\s+international\s+regulations)\b/gi,
        ]

        compoundPositivePatterns.forEach(pattern => {
            if (pattern.test(text)) {
                processedText += ' compound positive phrase detected'
                sentimentBoost += 0.6 // Strong boost for compound positive phrases
            }
        })

        // Special boost for your specific comment pattern
        const specificPositivePatterns = [
            /\b(initiative\s+by\s+the\s+government\s+ensures\s+that\s+the\s+country\s+meets)\b/gi,
            /\b(ensures\s+that\s+the\s+country\s+meets\s+sdg\s+goals)\b/gi,
            /\b(complies\s+with\s+the\s+international\s+rules\s+and\s+regulations)\b/gi,
            /\b(hence\s+the\s+initiative\s+by\s+the\s+government\s+is\s+commendable)\b/gi,
            /\b(therefore\s+.*\s+is\s+commendable)\b/gi,
            /\b(thus\s+.*\s+is\s+commendable)\b/gi,
            /\b(consequently\s+.*\s+is\s+commendable)\b/gi,
            /\b(as\s+a\s+result\s+.*\s+is\s+commendable)\b/gi,
        ]

        specificPositivePatterns.forEach(pattern => {
            if (pattern.test(text)) {
                processedText += ' specific positive governance pattern detected'
                sentimentBoost += 0.8 // Very strong boost for specific governance positive patterns
            }
        })

        this.sentimentPatterns.negative.forEach(pattern => {
            if (pattern.test(processedText)) {
                processedText += ' negative sentiment detected'
                sentimentBoost -= 0.3
            }
        })

        // Handle sarcasm (flip positive words in sarcastic context)
        this.sentimentPatterns.sarcasm.forEach(pattern => {
            if (pattern.test(text)) {
                processedText += ' sarcastic tone detected negative'
                sentimentBoost -= 0.4
            }
        })

        // Detect uncertainty (slightly negative bias)
        this.sentimentPatterns.uncertainty.forEach(pattern => {
            if (pattern.test(text)) {
                processedText += ' uncertainty detected'
                sentimentBoost -= 0.1
            }
        })

        // Detect emotional expressions
        this.sentimentPatterns.emotional.forEach(pattern => {
            if (pattern.test(text)) {
                processedText += ' emotional expression'
                // Context-dependent - could be positive or negative
            }
        })

        // Detect intensifiers
        const intensifierCount = this.sentimentPatterns.intensifiers.reduce((count, pattern) => {
            const matches = text.match(pattern)
            return count + (matches ? matches.length : 0)
        }, 0)

        if (intensifierCount > 0) {
            processedText += ` ${intensifierCount > 1 ? 'very ' : ''}intense`
        }

        // Detect negations
        const negationCount = this.sentimentPatterns.negations.reduce((count, pattern) => {
            const matches = text.match(pattern)
            return count + (matches ? matches.length : 0)
        }, 0)

        if (negationCount > 0) {
            processedText += ' negation detected'
            // Negations can flip sentiment, handled by VADER's built-in logic
        }

        // Handle enhanced vocabulary and context
        Object.entries(this.enhancedLexicon).forEach(([word, score]) => {
            const regex = new RegExp(`\\b${word}\\b`, 'gi')
            if (regex.test(processedText)) {
                if (score > 2.0) {
                    processedText = processedText.replace(regex, `${word} extremely`)
                } else if (score > 1.5) {
                    processedText = processedText.replace(regex, `${word} very`)
                } else if (score > 0.8) {
                    processedText = processedText.replace(regex, `${word} quite`)
                } else if (score < -2.0) {
                    processedText = processedText.replace(regex, `${word} extremely`)
                } else if (score < -1.5) {
                    processedText = processedText.replace(regex, `${word} very`)
                } else if (score < -0.8) {
                    processedText = processedText.replace(regex, `${word} quite`)
                }
            }
        })

        // Clean up extra spaces
        processedText = processedText.replace(/\s+/g, ' ').trim()

            // Store sentiment boost for later use in analysis
            (processedText as any).sentimentBoost = sentimentBoost

        return processedText
    }

    extractKeywords(text: string): string[] {
        const commonWords = [
            'the', 'is', 'at', 'which', 'on', 'and', 'a', 'to', 'are', 'as', 'was',
            'with', 'for', 'be', 'have', 'this', 'that', 'will', 'you', 'they', 'of',
            'it', 'in', 'or', 'an', 'but', 'not', 'can', 'we', 'should', 'would', 'could',
            'hai', 'hain', 'ka', 'ki', 'ke', 'ko', 'se', 'me', 'par', 'pe', 'bhi', 'aur',
            'ya', 'yah', 'woh', 'jo', 'jab', 'kab', 'kya', 'kaise', 'kyun', 'kahan'
        ]

        const words = text.toLowerCase().match(/\b\w+\b/g) || []

        return words
            .filter(word => word.length > 2 && !commonWords.includes(word))
            .reduce((acc: string[], word) => {
                if (!acc.includes(word)) acc.push(word)
                return acc
            }, [])
            .slice(0, 5)
    }

    countEmojis(text: string): number {
        const emojiRegex = /[\u{1F600}-\u{1F64F}]|[\u{1F300}-\u{1F5FF}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/gu
        const matches = text.match(emojiRegex)
        return matches ? matches.length : 0
    }

    analyzeComment(text: string, debateContext?: DebateContext): VADERAnalysis {
        try {
            if (!text || text.trim().length === 0) {
                return this.getNeutralAnalysis('Empty text')
            }

            // Preprocess text with advanced pattern detection
            const processedText = this.preprocessText(text)
            const emojiCount = this.countEmojis(text)
            const keywords = this.extractKeywords(processedText)

            // Get sentiment boost from pattern detection
            const sentimentBoost = (processedText as any).sentimentBoost || 0

            // Run VADER analysis
            const vaderResult = vader.SentimentIntensityAnalyzer.polarity_scores(processedText)

            // Apply pattern-based sentiment boost
            let adjustedCompound = vaderResult.compound + sentimentBoost

            // Apply custom thresholds for short comments
            let sentimentLabel: 'Positive' | 'Negative' | 'Neutral'

            if (adjustedCompound >= this.customThresholds.positive) {
                sentimentLabel = 'Positive'
            } else if (adjustedCompound <= this.customThresholds.negative) {
                sentimentLabel = 'Negative'
            } else {
                sentimentLabel = 'Neutral'
            }

            // Calculate confidence based on compound score magnitude and pattern detection
            let confidence = Math.min(100, Math.abs(adjustedCompound) * 100 + 20)

            // Boost confidence if patterns were detected
            if (Math.abs(sentimentBoost) > 0.2) {
                confidence += 15
            }

            // Boost confidence for emoji-rich short comments
            if (text.length < 50 && emojiCount > 0) {
                adjustedCompound *= 1.2
                confidence += 10
            }

            // Reduce confidence for very short text without context or patterns
            if (text.length < 10 && emojiCount === 0 && Math.abs(sentimentBoost) < 0.1) {
                adjustedCompound *= 0.7
                confidence -= 10
            }

            // Clamp compound score and confidence
            adjustedCompound = Math.max(-1, Math.min(1, adjustedCompound))
            confidence = Math.max(20, Math.min(100, confidence))

            return {
                sentiment_label: sentimentLabel,
                compound_score: Number(adjustedCompound.toFixed(3)),
                positive: Number(vaderResult.pos.toFixed(3)),
                negative: Number(vaderResult.neg.toFixed(3)),
                neutral: Number(vaderResult.neu.toFixed(3)),
                confidence: Math.round(confidence),
                keywords,
                emoji_count: emojiCount,
                processed_text: processedText
            }

        } catch (error) {
            console.error('VADER analysis error:', error)
            return this.getNeutralAnalysis('Analysis failed')
        }
    }

    private getNeutralAnalysis(reason: string): VADERAnalysis {
        return {
            sentiment_label: 'Neutral',
            compound_score: 0.0,
            positive: 0.0,
            negative: 0.0,
            neutral: 1.0,
            confidence: 30,
            keywords: [],
            emoji_count: 0,
            processed_text: reason
        }
    }

    compoundToAIScore(compoundScore: number, baseScore: number = 50): number {
        let aiScore = baseScore + (compoundScore * 25)

        const sentimentStrength = Math.abs(compoundScore)
        if (sentimentStrength > 0.5) {
            aiScore += 10
        } else if (sentimentStrength > 0.3) {
            aiScore += 5
        }

        return Math.min(100, Math.max(10, Math.round(aiScore)))
    }

    recalculateWithVotes(
        originalAnalysis: VADERAnalysis,
        votes: { agree: number; disagree: number; neutral: number }
    ): VADERAnalysis {
        const totalVotes = votes.agree + votes.disagree + votes.neutral

        if (totalVotes === 0) return originalAnalysis

        const agreementRatio = votes.agree / totalVotes
        const disagreementRatio = votes.disagree / totalVotes

        let adjustedCompound = originalAnalysis.compound_score

        if (agreementRatio > 0.7) {
            adjustedCompound = Math.min(1, adjustedCompound + 0.2)
        } else if (disagreementRatio > 0.7) {
            adjustedCompound = Math.max(-1, adjustedCompound - 0.2)
        }

        const engagementBonus = Math.min(20, totalVotes * 2)
        const adjustedConfidence = Math.min(100, originalAnalysis.confidence + engagementBonus)

        let newSentimentLabel: 'Positive' | 'Negative' | 'Neutral'
        if (adjustedCompound >= this.customThresholds.positive) {
            newSentimentLabel = 'Positive'
        } else if (adjustedCompound <= this.customThresholds.negative) {
            newSentimentLabel = 'Negative'
        } else {
            newSentimentLabel = 'Neutral'
        }

        return {
            ...originalAnalysis,
            sentiment_label: newSentimentLabel,
            compound_score: Number(adjustedCompound.toFixed(3)),
            confidence: adjustedConfidence
        }
    }

    async batchAnalyze(
        comments: Array<{ text: string; votes?: { agree: number; disagree: number; neutral: number } }>,
        debateContext?: DebateContext
    ): Promise<VADERAnalysis[]> {
        return comments.map(comment => {
            const analysis = this.analyzeComment(comment.text, debateContext)

            if (comment.votes) {
                return this.recalculateWithVotes(analysis, comment.votes)
            }

            return analysis
        })
    }

    getDebateSentiment(messages: VADERAnalysis[]): {
        overall_sentiment: 'Positive' | 'Negative' | 'Neutral'
        average_compound: number
        sentiment_distribution: { positive: number; negative: number; neutral: number }
        confidence: number
    } {
        if (messages.length === 0) {
            return {
                overall_sentiment: 'Neutral',
                average_compound: 0,
                sentiment_distribution: { positive: 0, negative: 0, neutral: 100 },
                confidence: 0
            }
        }

        const avgCompound = messages.reduce((sum, msg) => sum + msg.compound_score, 0) / messages.length

        const distribution = messages.reduce((acc, msg) => {
            acc[msg.sentiment_label.toLowerCase() as keyof typeof acc]++
            return acc
        }, { positive: 0, negative: 0, neutral: 0 })

        const total = messages.length
        const sentimentDistribution = {
            positive: Math.round((distribution.positive / total) * 100),
            negative: Math.round((distribution.negative / total) * 100),
            neutral: Math.round((distribution.neutral / total) * 100)
        }

        const overallSentiment: 'Positive' | 'Negative' | 'Neutral' =
            avgCompound >= this.customThresholds.positive ? 'Positive' :
                avgCompound <= this.customThresholds.negative ? 'Negative' : 'Neutral'

        const avgConfidence = messages.reduce((sum, msg) => sum + msg.confidence, 0) / messages.length

        return {
            overall_sentiment: overallSentiment,
            average_compound: Number(avgCompound.toFixed(3)),
            sentiment_distribution: sentimentDistribution,
            confidence: Math.round(avgConfidence)
        }
    }
}

export const vaderService = new VADERSentimentService()

// Test function for debugging sentiment analysis
export function testSentiment(text: string) {
    const result = vaderService.analyzeComment(text)
    console.log('Sentiment Analysis Test:')
    console.log('Input:', text)
    console.log('Result:', result)
    console.log('Processed Text:', result.processed_text)
    return result
}